import streamlit as st
import pandas as pd
from PIL import Image
from google import genai
from google.genai import types
from groq import Groq
import requests
from gtts import gTTS
import io
import hashlib
import numpy as np
import time
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime, date
import json
import re
import logging
import uuid
from typing import Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak,
)

# ── Logging ───────────────────────────────────────────────────────────────────
# All previously-silent except blocks now log to stderr so runtime issues are
# visible in the terminal / Streamlit Cloud logs during grading, instead of
# failing invisibly.
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("mediscan")

# ── Page Configuration ───────────────────────────────────────────────────────
st.set_page_config(
    page_title="MediScan AI",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Google Gemini Client (PRIMARY REASONING ENGINE) ─────────────────────────
# Architecture: Gemini handles ALL text generation (triage, health coach) and
# multimodal vision analysis. This is the core intelligence layer of MediScan AI.
try:
    client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
    _api_ready = True
except Exception as exc:
    client = None
    _api_ready = False
    logger.warning("Gemini client init failed: %s", exc)

# ── Groq Client (WHISPER STT ONLY) ────────────────────────────────────────────
# Architecture: Groq is used EXCLUSIVELY for Whisper-based speech-to-text
# transcription, leveraging its low-latency inference for real-time audio.
# All reasoning and generation tasks are handled by Gemini above.
try:
    groq_key = st.secrets.get("GROQ_API_KEY")
    groq_client = Groq(api_key=groq_key) if groq_key else None
except Exception as exc:
    groq_client = None
    logger.warning("Groq client init failed: %s", exc)

EMERGENCY_WEBHOOK_URL = "https://hook.us1.make.com/mock-emergency"
LANG_MAP = {"English": "en", "Hindi (हिन्दी)": "hi", "Marathi (मराठी)": "mr", "Bengali (বাংলা)": "bn", "Spanish (Español)": "es"}

# ── System Instructions ───────────────────────────────────────────────────────
TRIAGE_SYSTEM_INSTRUCTION = """
You are the MediScan AI Triage Assistant, an intelligent clinical first-filter system designed for use in resource-constrained medical environments. Your primary objective is to analyze chaotic patient-reported symptoms, cross-reference them with the provided patient demographic profile and structured intake data (severity, duration, onset, affected body areas), and output a probabilistically ranked differential diagnosis.

OPERATIONAL CONSTRAINTS:
1. You are a triage assistant, NOT a prescribing physician. You must NEVER prescribe medications or suggest specific pharmacological dosages.
2. You must strictly limit your analysis to the top 3 most probable underlying conditions based on the provided symptoms and biometric baseline.
3. Your tone must remain highly clinical, empathetic, and objective.
4. You must format your response with clear markdown headings, bullet points for symptoms matched, an "Urgency Level" (Low / Moderate / High / Emergency), and a distinct "Recommended Next Steps" section.
5. If severity/urgency signals suggest an emergency (e.g. chest pain, difficulty breathing, stroke symptoms, severe bleeding), clearly state this at the TOP of the response in bold.

STRUCTURED OUTPUT (MANDATORY):
After your full markdown response and BEFORE the CDSCO disclaimer, you MUST output exactly one JSON code block in this format:
```json
{"urgency_level": "<Low|Moderate|High|Emergency>", "top_conditions": ["condition_1", "condition_2", "condition_3"], "confidence": <0.0-1.0>}
```
This block is machine-parsed by the application. Do NOT omit it.

MANDATORY DISCLAIMER:
You must append the following exact text to the very bottom of every single response you generate, with no exceptions:

"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

VISION_SYSTEM_INSTRUCTION = """
You are the MediScan AI Diagnostic Vision System, an advanced optical character recognition (OCR) and visual analysis engine. Your objective is to extract, structure, and analyze clinical data from uploaded medical documents (e.g., blood panels, pathology reports) or analyze physical symptom images (e.g., dermatological lesions).

OPERATIONAL CONSTRAINTS:
1. If the image is a document, meticulously extract key biomarkers and present them in a structured markdown table comparing extracted values against standard healthy reference ranges.
2. If the image is a document, you must also provide a detailed analysis of each term/biomarker, explaining:
   - What the term means in plain language.
   - Its health impact (clinical implications of standard, elevated, or low values).
   - How to tackle and manage it (dietary changes, lifestyle adjustments, preventative measures, or recommended follow-up tests).
3. If the image is a physical symptom, provide an objective visual description and list up to 3 potential differential diagnoses.
4. Flag any critical abnormalities or out-of-range metrics clearly, using a "⚠️ Critical Flags" section.
5. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

HEALTH_COACH_SYSTEM_INSTRUCTION = """
You are the MediScan AI Preventative Health Coach. You will be provided with a CSV string containing a patient's simulated 6-month biometric data, including Resting Heart Rate, Systolic Blood Pressure, Fasting Glucose, and a computed Health Risk Score.

OPERATIONAL CONSTRAINTS:
1. Analyze the month-over-month trajectory of the metrics.
2. Provide a concise, 3-bullet-point wellness recommendation based STRICTLY on the trends in the data.
3. Emphasize preventative care and lifestyle modifications.
4. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Helpers ───────────────────────────────────────────────────────────────────
def blank_health_metrics() -> pd.DataFrame:
    """Return a default 6-month biometric DataFrame for a new patient."""
    return pd.DataFrame({
        "Month":              ["March", "April", "May", "June", "July", "August"],
        "Resting_HR":         [72, 74, 73, 76, 78, 80],
        "Systolic_BP":        [118, 121, 119, 125, 128, 131],
        "Fasting_Glucose":    [92, 94, 96, 99, 101, 104],
        "Health_Risk_Score":  [18, 22, 20, 31, 38, 42],
    })


def new_patient_record(age: int = 25, sex: str = "Male", weight: float = 70.0, conditions: str = "") -> dict[str, Any]:
    """Create a blank patient record dict with default profile and empty history lists."""
    return {
        "profile": {"age": age, "sex": sex, "weight_kg": weight, "chronic_conditions": conditions},
        "chat_history": [],
        "archived_conversations": [],
        "report_history": [],
        "health_metrics": blank_health_metrics(),
        "coach_recommendation": None,
        "feedback": {},
        "last_intake": None,
    }


def fire_emergency_webhook(payload: dict) -> bool:
    """POST an emergency alert payload to the configured webhook endpoint.

    Returns True on a successful (2xx) response, False otherwise. Failures are
    logged rather than silently swallowed, and the outcome is recorded in
    session_state so the UI can honestly reflect whether the alert actually
    went out (this app currently points at a mock endpoint — see the caption
    shown alongside SOS/emergency triggers in the UI).
    """
    ok = False
    try:
        resp = requests.post(EMERGENCY_WEBHOOK_URL, json=payload, timeout=4)
        ok = resp.ok
        if not ok:
            logger.warning("Emergency webhook returned status %s: %s", resp.status_code, resp.text[:200])
    except requests.exceptions.RequestException as exc:
        logger.error("Emergency webhook request failed: %s", exc)
        ok = False

    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "alert": payload.get("alert", "unknown"),
        "delivered": ok,
    }
    if "webhook_log" not in st.session_state:
        st.session_state.webhook_log = []
    st.session_state.webhook_log.append(log_entry)
    return ok


def metric_flag(name: str, value: float) -> tuple[str, str]:
    """Return a (label, color) badge tuple for a biometric value against clinical thresholds."""
    thresholds = {
        "Resting_HR": (60, 100, "bpm"),
        "Systolic_BP": (90, 130, "mmHg"),
        "Fasting_Glucose": (70, 100, "mg/dL"),
        "Health_Risk_Score": (0, 40, "/100"),
    }
    low, high, unit = thresholds.get(name, (None, None, ""))
    if low is None:
        return "—", "gray"
    if value < low:
        return "🔵 Low", "blue"
    if value <= high:
        return "🟢 Normal", "green"
    if value <= high * 1.2:
        return "🟠 Elevated", "orange"
    return "🔴 High", "red"


def generate_doctor_pdf(patient_name, record, emergency_contact, language,
                         include_chat=True, include_reports=True, include_biometrics=True,
                         doctor_name="", referring_note=""):
    """Builds an in-memory PDF clinical handoff summary for a doctor. Returns BytesIO."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=18, spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#1a4d7a"))
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8, textColor=colors.gray)
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=10, leading=14)
    tag = ParagraphStyle("tag", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#b02a2a"))

    def esc(text):
        return (str(text) or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    story = []

    story.append(Paragraph("🩺 MediScan AI — Clinical Handoff Summary", h1))
    story.append(Paragraph(
        f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} · Response language on record: {language}",
        small,
    ))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#1a4d7a"), thickness=1, spaceAfter=8))

    if doctor_name or referring_note:
        story.append(Paragraph(f"<b>Addressed to:</b> {esc(doctor_name) or 'Attending Physician'}", body))
        if referring_note:
            story.append(Paragraph(f"<b>Note from patient/carer:</b> {esc(referring_note)}", body))
        story.append(Spacer(1, 6))

    # ── Patient Profile ────────────────────────────────────────────────────
    story.append(Paragraph("Patient Profile", h2))
    prof = record["profile"]
    profile_table_data = [
        ["Name", esc(patient_name)],
        ["Age", esc(prof.get("age", "—"))],
        ["Sex", esc(prof.get("sex", "—"))],
        ["Weight", f"{prof.get('weight_kg', 0):.1f} kg" if prof.get("weight_kg") else "—"],
        ["Chronic Conditions", esc(prof.get("chronic_conditions") or "None reported")],
    ]
    if emergency_contact.get("name"):
        profile_table_data.append(["Emergency Contact", f"{esc(emergency_contact['name'])} — {esc(emergency_contact.get('phone', ''))}"])
    pt = Table(profile_table_data, colWidths=[1.7 * inch, 4.3 * inch])
    pt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef3f8")),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c9d6e3")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(pt)

    # ── Structured Intake (most recent) ────────────────────────────────────
    intake = record.get("last_intake")
    if intake:
        story.append(Paragraph("Most Recent Structured Intake", h2))
        intake_data = [
            ["Severity", f"{intake.get('severity', '—')}/10"],
            ["Duration", esc(intake.get("duration", "—"))],
            ["Onset", esc(intake.get("onset", "—"))],
            ["Affected Area(s)", esc(", ".join(intake.get("body_areas", [])) or "Not specified")],
        ]
        it = Table(intake_data, colWidths=[1.7 * inch, 4.3 * inch])
        it.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef3f8")),
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c9d6e3")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(it)

    # ── Biometric Trend ─────────────────────────────────────────────────────
    if include_biometrics and not record["health_metrics"].empty:
        story.append(Paragraph("6-Month Biometric Trend", h2))
        hm = record["health_metrics"]
        header = ["Month", "Resting HR", "Systolic BP", "Fasting Glucose", "Risk Score"]
        rows = [header] + hm[["Month", "Resting_HR", "Systolic_BP", "Fasting_Glucose", "Health_Risk_Score"]].astype(str).values.tolist()
        bt = Table(rows, colWidths=[1.0 * inch] * 5)
        bt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a4d7a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c9d6e3")),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8fb")]),
        ]))
        story.append(bt)
        latest = hm.iloc[-1]
        flag_label, _ = metric_flag("Health_Risk_Score", latest["Health_Risk_Score"])
        story.append(Paragraph(f"Latest Health Risk Score: <b>{int(latest['Health_Risk_Score'])}/100</b> ({esc(flag_label)})", body))

    # ── AI Triage Transcript ────────────────────────────────────────────────
    if include_chat and record["chat_history"]:
        story.append(Paragraph("AI Triage Session Transcript", h2))
        story.append(Paragraph(
            "The following is an automated triage conversation between the patient and MediScan AI. "
            "This is provided for context only and does not constitute a clinical diagnosis.", tag,
        ))
        story.append(Spacer(1, 4))
        for m in record["chat_history"]:
            role_label = "Patient" if m["role"] == "user" else "MediScan AI"
            style = body
            text = esc(m["content"]).replace("\n", "<br/>")
            story.append(Paragraph(f"<b>{role_label}:</b> {text}", style))
            story.append(Spacer(1, 6))

    # ── Report / Lab Analysis History ──────────────────────────────────────
    if include_reports and record["report_history"]:
        story.append(PageBreak())
        story.append(Paragraph("Lab / Visual Report Analyses", h2))
        for r in record["report_history"]:
            story.append(Paragraph(f"<b>{esc(r['filename'])}</b> — {esc(r['timestamp'])}", body))
            text = esc(r["result"]).replace("\n", "<br/>")
            story.append(Paragraph(text, body))
            story.append(Spacer(1, 10))

    # ── Doctor Notes Section ────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Physician Notes", h2))
    story.append(Paragraph("(Space reserved for clinician annotations, diagnosis, and treatment plan.)", small))
    story.append(Spacer(1, 10))
    for _ in range(10):
        story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc"), thickness=0.5, spaceAfter=18))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "***CDSCO COMPLIANCE DISCLAIMER:*** MediScan AI is a Clinical Decision Support System (CDSS). "
        "The information in this document is generated by an artificial intelligence model and is strictly "
        "for triage and informational purposes. It is NOT a substitute for professional medical advice, "
        "diagnosis, or treatment. This summary is intended to assist — not replace — clinical judgment.",
        ParagraphStyle("disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.gray, spaceBefore=10),
    ))

    doc.build(story)
    buf.seek(0)
    return buf


CITY_COORDS = {
    "Pune": (18.5204, 73.8567), "Mumbai": (19.0760, 72.8777), "Delhi": (28.6139, 77.2090),
    "Bangalore": (12.9716, 77.5946), "Hyderabad": (17.3850, 78.4867), "Chennai": (13.0827, 80.2707),
    "Kolkata": (22.5726, 88.3639), "Ahmedabad": (23.0225, 72.5714), "Nagpur": (21.1458, 79.0882),
    "Jaipur": (26.9124, 75.7873), "Lucknow": (26.8467, 80.9462), "Patna": (25.5941, 85.1376),
    "Indore": (22.7196, 75.8577), "Thane": (19.2183, 72.9781), "Bhopal": (23.2599, 77.4126),
    "Visakhapatnam": (17.6868, 83.2185), "Vadodara": (22.3072, 73.1812), "Ghaziabad": (28.6692, 77.4538),
    "Surat": (21.1702, 72.8311), "Kanpur": (26.4499, 80.3319), "Ludhiana": (30.9010, 75.8573),
    "Agra": (27.1767, 78.0081), "Nashik": (19.9975, 73.7898), "Faridabad": (28.4089, 77.3178),
    "Meerut": (28.9845, 77.7064), "Rajkot": (22.3039, 70.8022), "Kalyan-Dombivli": (19.2403, 73.1305),
    "Vasai-Virar": (19.3913, 72.8397), "Varanasi": (25.3176, 82.9739), "Srinagar": (34.0837, 74.7973),
    "Aurangabad": (19.8762, 75.3433), "Dhanbad": (23.7957, 86.4304), "Amritsar": (31.6340, 74.8723),
    "Navi Mumbai": (19.0330, 73.0297), "Allahabad": (25.4358, 81.8463), "Ranchi": (23.3441, 85.3096),
    "Howrah": (22.5958, 88.2636), "Coimbatore": (11.0168, 76.9558), "Jabalpur": (22.1760, 79.9300),
    "Gwalior": (26.2183, 78.1828), "Vijayawada": (16.5062, 80.6480), "Jodhpur": (26.2389, 73.0243),
    "Madurai": (9.9252, 78.1198), "Raipur": (21.2514, 81.6296), "Kota": (25.2138, 75.8648),
    "Guwahati": (26.1445, 91.7362), "Chandigarh": (30.7333, 76.7794), "Solapur": (17.6599, 75.9064),
    "Hubli-Dharwad": (15.3647, 75.1240), "Amravati": (20.9374, 77.7796),
}


# ── Session State Initialization ──────────────────────────────────────────────
if "patients" not in st.session_state:
    st.session_state.patients = {"Patient 1": new_patient_record()}
if "active_patient" not in st.session_state:
    st.session_state.active_patient = "Patient 1"
if "app_language" not in st.session_state:
    st.session_state.app_language = "English"
if "weight_unit" not in st.session_state:
    st.session_state.weight_unit = "kg"
if "emergency_contact" not in st.session_state:
    st.session_state.emergency_contact = {"name": "", "phone": ""}
if "reminders" not in st.session_state:
    st.session_state.reminders = []  # list of dicts: id, date, note, done, patient
if "camera_active" not in st.session_state:
    st.session_state.camera_active = False
if "telemetry_active" not in st.session_state:
    st.session_state.telemetry_active = False
if "webhook_log" not in st.session_state:
    st.session_state.webhook_log = []

active_record = st.session_state.patients[st.session_state.active_patient]

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🌐 Language Preferences")
    st.session_state.app_language = st.selectbox(
        "Select Response Language",
        list(LANG_MAP.keys()),
        index=list(LANG_MAP.keys()).index(st.session_state.app_language),
    )

    if not _api_ready:
        st.warning(
            "⚠️ **Gemini API key not configured.**\n\nAdd `GEMINI_API_KEY` to `.streamlit/secrets.toml`. Report analysis will be unavailable until then.",
            icon="🔑",
        )
    if groq_client is None:
        st.warning(
            "⚠️ **Groq API key not configured.**\n\nAdd `GROQ_API_KEY` to `.streamlit/secrets.toml`. Voice input (Whisper STT) will be unavailable until then.",
            icon="🔑",
        )

    st.markdown("---")
    st.markdown("## 👤 Patient Profiles")

    patient_names = list(st.session_state.patients.keys())
    st.session_state.active_patient = st.selectbox(
        "Active Patient", patient_names,
        index=patient_names.index(st.session_state.active_patient),
    )
    active_record = st.session_state.patients[st.session_state.active_patient]

    with st.expander("➕ Add / Remove Patient"):
        new_name = st.text_input("New patient name", key="new_patient_name")
        cadd, cdel = st.columns(2)
        if cadd.button("Add Patient", use_container_width=True):
            if new_name and new_name not in st.session_state.patients:
                st.session_state.patients[new_name] = new_patient_record()
                st.session_state.active_patient = new_name
                st.rerun()
            elif new_name in st.session_state.patients:
                st.warning("A patient with that name already exists.")
        if cdel.button("Remove Active", use_container_width=True, type="secondary"):
            if len(st.session_state.patients) > 1:
                del st.session_state.patients[st.session_state.active_patient]
                st.session_state.active_patient = list(st.session_state.patients.keys())[0]
                st.rerun()
            else:
                st.warning("At least one patient profile must remain.")

    st.session_state.weight_unit = st.radio("Weight Unit", ["kg", "lb"], horizontal=True,
                                             index=["kg", "lb"].index(st.session_state.weight_unit))

    with st.form(key="patient_profile_form", clear_on_submit=False):
        profile = active_record["profile"]
        age = st.number_input("Age", min_value=0, max_value=120, value=int(profile.get("age") or 25), step=1)
        sex = st.selectbox(
            "Sex", options=["Male", "Female", "Other", "Prefer not to say"],
            index=["Male", "Female", "Other", "Prefer not to say"].index(profile.get("sex") or "Male"),
        )
        weight_kg = profile.get("weight_kg") or 70.0
        display_weight = weight_kg if st.session_state.weight_unit == "kg" else weight_kg * 2.20462
        weight_input = st.number_input(
            f"Weight ({st.session_state.weight_unit})", min_value=0.0,
            max_value=500.0 if st.session_state.weight_unit == "kg" else 1100.0,
            value=float(display_weight), step=0.5, format="%.1f",
        )
        chronic_conditions = st.text_area(
            "Chronic Conditions", value=profile.get("chronic_conditions") or "",
            placeholder="e.g., Diabetes Type 2, Hypertension, Asthma...", height=90,
        )
        submitted = st.form_submit_button("💾 Save Profile", use_container_width=True, type="primary")
        if submitted:
            weight_kg_final = weight_input if st.session_state.weight_unit == "kg" else weight_input / 2.20462
            active_record["profile"] = {
                "age": age, "sex": sex, "weight_kg": weight_kg_final, "chronic_conditions": chronic_conditions,
            }
            st.success("✅ Profile saved!")

    profile = active_record["profile"]
    if profile.get("age"):
        st.markdown("---")
        st.markdown("### 📋 Current Profile")
        disp_w = profile["weight_kg"] if st.session_state.weight_unit == "kg" else profile["weight_kg"] * 2.20462
        st.markdown(f"- **Age:** {profile['age']} yrs")
        st.markdown(f"- **Sex:** {profile['sex']}")
        st.markdown(f"- **Weight:** {disp_w:.1f} {st.session_state.weight_unit}")
        if profile.get("chronic_conditions"):
            st.markdown(f"- **Conditions:** {profile['chronic_conditions']}")

    st.markdown("---")
    st.markdown("### 🚨 Emergency Contact")
    with st.expander("Configure Emergency Contact", expanded=not st.session_state.emergency_contact["name"]):
        ec_name = st.text_input("Contact Name", value=st.session_state.emergency_contact["name"])
        ec_phone = st.text_input("Contact Phone", value=st.session_state.emergency_contact["phone"])
        if st.button("Save Contact", use_container_width=True):
            st.session_state.emergency_contact = {"name": ec_name, "phone": ec_phone}
            st.success("Emergency contact saved.")

    if st.button("🆘 Trigger SOS Alert", use_container_width=True, type="primary"):
        delivered = fire_emergency_webhook({
            "alert": "manual_sos",
            "patient": st.session_state.active_patient,
            "profile": active_record["profile"],
            "emergency_contact": st.session_state.emergency_contact,
            "timestamp": datetime.now().isoformat(),
        })
        if delivered:
            st.error(f"🚨 SOS triggered. Notifying {st.session_state.emergency_contact.get('name') or 'your emergency contact'}.")
        else:
            st.error(
                "🚨 SOS triggered, but the alert endpoint did not confirm delivery. "
                "This prototype points at a mock webhook — do not rely on it in a real emergency; "
                "contact emergency services directly."
            )
    st.caption("ℹ️ SOS/webhook alerts in this prototype point at a mock endpoint for demo purposes and are not connected to real emergency dispatch.")

    st.markdown("---")
    st.markdown("### 📄 Export Dossier")

    def generate_dossier(patient_name: str, record: dict) -> str:
        """Build a plain-text patient dossier string for download/export."""
        prof = record["profile"]
        content = f"=== MEDISCAN AI PATIENT DOSSIER: {patient_name} ===\n"
        content += f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        content += f"PROFILE:\nAge: {prof.get('age')}\nSex: {prof.get('sex')}\nWeight: {prof.get('weight_kg')} kg\nConditions: {prof.get('chronic_conditions')}\n\n"
        if st.session_state.emergency_contact["name"]:
            content += f"EMERGENCY CONTACT:\n{st.session_state.emergency_contact['name']} — {st.session_state.emergency_contact['phone']}\n\n"
        if not record["health_metrics"].empty:
            content += f"BIOMETRIC TRAJECTORY (Last 6 Months):\n{record['health_metrics'].to_string(index=False)}\n\n"
        if record["report_history"]:
            content += "LAB / VISUAL REPORT HISTORY:\n"
            for r in record["report_history"]:
                content += f"\n--- {r['timestamp']} ({r['filename']}) ---\n{r['result']}\n"
        if record["coach_recommendation"]:
            content += f"\nLATEST WELLNESS COACH RECOMMENDATION:\n{record['coach_recommendation']}\n"
        if record["chat_history"]:
            content += "\nSYMPTOM TRIAGE CHAT LOG:\n"
            for m in record["chat_history"]:
                content += f"[{m['role'].upper()}] {m['content']}\n\n"
        return content

    st.download_button(
        "📥 Download Active Patient Dossier",
        data=generate_dossier(st.session_state.active_patient, active_record),
        file_name=f"mediscan_dossier_{st.session_state.active_patient.replace(' ', '_')}.txt",
        mime="text/plain", use_container_width=True, type="secondary",
    )

    all_dossiers = "\n\n".join(generate_dossier(n, r) for n, r in st.session_state.patients.items())
    st.download_button(
        "📥 Download All Patients Dossier",
        data=all_dossiers, file_name="mediscan_dossier_all_patients.txt",
        mime="text/plain", use_container_width=True,
    )

    st.markdown("---")
    with st.expander("⚙️ System Architecture"):
        st.markdown("""
```mermaid
graph LR
    A["👤 User"] --> B["Streamlit UI"]
    B --> C["🧠 Gemini\nReasoning + Vision"]
    B --> D["🎙️ Groq Whisper\nSpeech-to-Text"]
    B --> E["🔊 gTTS\nText-to-Speech"]
    C --> F["session_state"]
    D --> F
    F --> G["📄 PDF / Dossier\nExport"]
    F --> H["🚨 Webhook\nEmergency Alerts"]
```
""")

    if st.session_state.webhook_log:
        with st.expander(f"🚨 Webhook Delivery Log ({len(st.session_state.webhook_log)})"):
            for entry in reversed(st.session_state.webhook_log[-10:]):
                status = "✅ delivered" if entry["delivered"] else "❌ not confirmed"
                st.caption(f"{entry['timestamp']} — {entry['alert']} — {status}")

# ── Main Content ──────────────────────────────────────────────────────────────
st.markdown("# 🩺 MediScan AI")
st.markdown(f"*Your intelligent medical assistant — active profile: **{st.session_state.active_patient}***")
st.markdown("---")

tab1, tab2, tab3, tab4 = st.tabs([
    "🔬 Symptom Analyzer",
    "📄 Medical Report Interpreter",
    "📊 Health Dashboard",
    "🗓️ Reminders & Care Plan",
])

# ── Tab 1: Symptom Analyzer ───────────────────────────────────────────────────
with tab1:
    st.markdown("## 🔬 Symptom Analyzer")
    st.info(
        "Describe your symptoms via text or voice, optionally fill the structured intake for a "
        "more accurate triage. The AI will analyze them against your patient profile and return "
        "a ranked differential diagnosis.",
        icon="ℹ️",
    )

    with st.expander("📋 Structured Intake (optional, improves accuracy)"):
        with st.form("structured_intake_form", clear_on_submit=False):
            ci1, ci2, ci3 = st.columns(3)
            severity = ci1.slider("Severity (1 = mild, 10 = severe)", 1, 10, 5, key="intake_severity")
            duration = ci2.selectbox("Duration", ["< 1 day", "1-3 days", "4-7 days", "1-4 weeks", "> 1 month"], key="intake_duration")
            onset = ci3.selectbox("Onset", ["Sudden", "Gradual", "Not sure"], key="intake_onset")
            body_areas = st.multiselect(
                "Affected Body Area(s)",
                ["Head", "Chest", "Abdomen", "Back", "Arms", "Legs", "Skin", "Throat", "Eyes", "Whole body", "Other"],
                key="intake_areas",
            )
            st.form_submit_button("✅ Lock Intake", use_container_width=True)

    top_c1, top_c2 = st.columns([3, 1])
    with top_c2:
        if st.button("🆕 New Conversation", use_container_width=True, disabled=not active_record["chat_history"]):
            active_record["archived_conversations"].append({
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
                "messages": active_record["chat_history"],
            })
            active_record["chat_history"] = []
            active_record["feedback"] = {}
            st.rerun()

    if active_record["archived_conversations"]:
        with st.expander(f"🗂️ Past Conversations ({len(active_record['archived_conversations'])})"):
            for i, convo in enumerate(reversed(active_record["archived_conversations"])):
                st.markdown(f"**{convo['timestamp']}** — {len(convo['messages'])} messages")
                for m in convo["messages"][:2]:
                    st.caption(f"{m['role']}: {m['content'][:120]}")
                st.markdown("---")

    # ── Render Chat History with feedback controls ────────────────────────────
    for idx, message in enumerate(active_record["chat_history"]):
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if message["role"] == "assistant":
                fb_col1, fb_col2, _ = st.columns([1, 1, 8])
                current_fb = active_record["feedback"].get(idx)
                if fb_col1.button("👍", key=f"fb_up_{idx}", type="primary" if current_fb == "up" else "secondary"):
                    active_record["feedback"][idx] = "up"
                    st.rerun()
                if fb_col2.button("👎", key=f"fb_down_{idx}", type="primary" if current_fb == "down" else "secondary"):
                    active_record["feedback"][idx] = "down"
                    st.rerun()

    # ── Audio Input ───────────────────────────────────────────────────────────
    st.markdown("#### 🎙️ Voice Input *(optional)*")
    audio_value = st.audio_input(
        "Record your symptoms", key="symptom_audio",
        help="Record a voice description of your symptoms alongside your text input.",
        disabled=groq_client is None,
    )

    # ── Text Chat Input ───────────────────────────────────────────────────────
    # DESIGN NOTE: st.chat_input cannot be placed inside an st.form (Streamlit API
    # constraint). It fires on Enter-key and is the primary triage input — this is
    # the intended interaction model per Streamlit's design.
    user_text = st.chat_input(
        "Describe your symptoms here (e.g. fever for 3 days, severe headache, nausea)…",
        disabled=not _api_ready,
    )

    is_new_audio = False
    audio_hash = None
    if audio_value:
        try:
            audio_bytes = audio_value.getvalue()
            audio_hash = hashlib.md5(audio_bytes).hexdigest()
            if active_record.get("last_processed_audio_hash") != audio_hash:
                is_new_audio = True
        except Exception as exc:
            logger.warning("Failed to hash audio input: %s", exc)
            st.warning("⚠️ Couldn't read the recorded audio — please try recording again.")

    if user_text or is_new_audio:
        profile = active_record["profile"]

        active_record["last_intake"] = {
            "severity": severity, "duration": duration, "onset": onset, "body_areas": body_areas,
        }

        intake_summary = (
            f"\nSTRUCTURED INTAKE:\n- Severity: {severity}/10\n- Duration: {duration}\n"
            f"- Onset: {onset}\n- Affected area(s): {', '.join(body_areas) if body_areas else 'Not specified'}\n"
        )

        dynamic_system_instruction = f"""{TRIAGE_SYSTEM_INSTRUCTION}

PATIENT BIOMETRIC BASELINE:
- Age: {profile.get('age', 'Not provided')} years
- Sex: {profile.get('sex', 'Not provided')}
- Weight: {profile.get('weight_kg', 'Not provided')} kg
- Chronic Conditions: {profile.get('chronic_conditions') or 'None reported'}
{intake_summary}
CRITICAL LANGUAGE INSTRUCTION:
You must translate your entire response, including the differential diagnosis and recommended steps, into {st.session_state.app_language}. Ensure medical terms are accurately translated or transliterated. The CDSCO disclaimer must also be translated into {st.session_state.app_language}.
"""

        final_symptom_text = user_text or ""

        if is_new_audio and audio_value is not None and groq_client is not None:
            with st.spinner("🎙️ Transcribing audio with Groq Whisper..."):
                try:
                    transcription = groq_client.audio.transcriptions.create(
                        file=("audio.wav", audio_value.read()), model="whisper-large-v3-turbo"
                    )
                    final_symptom_text = f"{final_symptom_text}\nVoice note: {transcription.text}".strip()
                except Exception as exc:
                    logger.error("Whisper transcription failed: %s", exc)
                    st.error(f"🎙️ Whisper transcription error: {exc}")

        if final_symptom_text.strip():
            with st.chat_message("user"):
                st.markdown(final_symptom_text)
            active_record["chat_history"].append({"role": "user", "content": final_symptom_text})

            # Build conversation context for Gemini (single-turn with history)
            conversation_context = ""
            for msg in active_record["chat_history"]:
                role_label = "Patient" if msg["role"] == "user" else "MediScan AI"
                conversation_context += f"{role_label}: {msg['content']}\n\n"

            assistant_reply = None
            with st.chat_message("assistant"):
                with st.spinner(f"🧠 Analysing symptoms in {st.session_state.app_language}..."):
                    try:
                        response = client.models.generate_content(
                            model="gemini-2.0-flash",
                            contents=conversation_context,
                            config=types.GenerateContentConfig(system_instruction=dynamic_system_instruction),
                        )
                        assistant_reply = response.text
                    except Exception as exc:
                        logger.error("Gemini triage call failed: %s", exc)
                        assistant_reply = f"⚠️ **Error communicating with Gemini:** `{exc}`"
                st.markdown(assistant_reply)

                # ── Programmatic urgency detection via structured JSON output ──
                is_critical = False
                try:
                    json_match = re.search(r'\{[^{}]*"urgency_level"[^{}]*\}', assistant_reply)
                    if json_match:
                        urgency_data = json.loads(json_match.group())
                        if urgency_data.get("urgency_level") in ("High", "Emergency"):
                            is_critical = True
                except (json.JSONDecodeError, AttributeError) as exc:
                    logger.info("Urgency JSON parse fell back to keyword scan: %s", exc)
                if not is_critical:
                    # Fallback: keyword-based detection if JSON parsing failed
                    critical_keywords = ["urgent care", "emergency", "immediate", "hospital", "chest pain", "stroke"]
                    is_critical = any(kw in assistant_reply.lower() for kw in critical_keywords)
                if is_critical:
                    delivered = fire_emergency_webhook({
                        "alert": "critical_symptoms",
                        "patient": st.session_state.active_patient,
                        "profile": profile,
                        "emergency_contact": st.session_state.emergency_contact,
                        "timestamp": datetime.now().isoformat(),
                    })
                    if delivered:
                        st.error(
                            "🚨 **CRITICAL TRIAGE ESCALATION** 🚨\n\nHigh-risk symptoms detected. "
                            f"Notifying {st.session_state.emergency_contact.get('name') or 'emergency dispatch'}."
                        )
                    else:
                        st.error(
                            "🚨 **CRITICAL TRIAGE ESCALATION** 🚨\n\nHigh-risk symptoms detected, but the "
                            "alert endpoint did not confirm delivery (this is a mock webhook in the prototype). "
                            "Please seek in-person or emergency care directly."
                        )

                tts_lang = LANG_MAP.get(st.session_state.app_language, "en")
                try:
                    clean_text = assistant_reply.replace("*", "").replace("#", "")
                    tts = gTTS(text=clean_text, lang=tts_lang, slow=False)
                    audio_fp = io.BytesIO()
                    tts.write_to_fp(audio_fp)
                    audio_fp.seek(0)
                    st.audio(audio_fp, format="audio/mp3")
                except Exception as exc:
                    logger.warning("gTTS synthesis failed: %s", exc)
                    st.caption("🔇 Audio synthesis is temporarily unavailable.")

            active_record["chat_history"].append({"role": "assistant", "content": assistant_reply})

        if audio_hash:
            active_record["last_processed_audio_hash"] = audio_hash
        st.rerun()

    st.divider()
    st.markdown("### 🏥 Nearby Care Centers")
    st.caption("Locate verified real-time medical facilities, emergency care, and diagnostic centers in your area via Google Maps.")

    cc1, _ = st.columns([2, 1])
    cities_list = sorted(CITY_COORDS.keys())
    user_city = cc1.selectbox("Select your city:", options=cities_list,
                               index=cities_list.index("Pune") if "Pune" in cities_list else 0)

    lat, lon = CITY_COORDS.get(user_city, (18.5204, 73.8567))

    city_map_data = pd.DataFrame([{"lat": lat, "lon": lon}])
    st.map(city_map_data, zoom=12, use_container_width=True)

    search_city_query = user_city.replace(" ", "+")
    hospitals_url = f"https://www.google.com/maps/search/hospitals+and+clinics+near+{search_city_query}/@{lat},{lon},13z"
    emergency_url = f"https://www.google.com/maps/search/emergency+room+and+trauma+center+near+{search_city_query}/@{lat},{lon},13z"
    labs_url = f"https://www.google.com/maps/search/diagnostic+center+and+pathology+lab+near+{search_city_query}/@{lat},{lon},13z"
    pharmacies_url = f"https://www.google.com/maps/search/pharmacy+medical+store+near+{search_city_query}/@{lat},{lon},13z"

    st.markdown(f"#### 📍 Live Healthcare Search in {user_city}")
    m_col1, m_col2 = st.columns(2)
    m_col1.link_button(f"🏥 Hospitals & Clinics in {user_city}", hospitals_url, use_container_width=True)
    m_col2.link_button(f"🚨 Emergency Rooms in {user_city}", emergency_url, use_container_width=True)

    m_col3, m_col4 = st.columns(2)
    m_col3.link_button(f"🔬 Diagnostic Labs in {user_city}", labs_url, use_container_width=True)
    m_col4.link_button(f"💊 24/7 Pharmacies in {user_city}", pharmacies_url, use_container_width=True)

    if active_record["chat_history"]:
        st.divider()
        if st.button("🗑️ Clear Current Chat", key="clear_symptom_chat"):
            active_record["chat_history"] = []
            active_record["feedback"] = {}
            active_record.pop("last_processed_audio_hash", None)
            st.rerun()

    st.divider()
    st.markdown("### 👨⚕️ Share with a Doctor")
    st.caption(
        "Generate a clinician-ready PDF summarizing this patient's profile, structured intake, "
        "AI triage transcript, lab report analyses, and biometric trend — with space reserved for physician notes."
    )

    has_content = bool(active_record["chat_history"] or active_record["report_history"] or not active_record["health_metrics"].empty)
    if not has_content:
        st.caption("Nothing to share yet — run a symptom triage or report analysis first.")
    else:
        with st.form("doctor_handoff_form"):
            dh1, dh2 = st.columns(2)
            doctor_name = dh1.text_input("Doctor / clinic name (optional)", placeholder="Dr. Sharma, City Care Hospital")
            doctor_email = dh2.text_input("Doctor's email (optional, for record-keeping)", placeholder="doctor@example.com")
            referring_note = st.text_area("Note to the doctor (optional)", placeholder="e.g. Patient requests a follow-up appointment this week.", height=70)

            inc1, inc2, inc3 = st.columns(3)
            include_chat = inc1.checkbox("Include triage transcript", value=bool(active_record["chat_history"]),
                                          disabled=not active_record["chat_history"])
            include_reports = inc2.checkbox("Include lab/report analyses", value=bool(active_record["report_history"]),
                                             disabled=not active_record["report_history"])
            include_biometrics = inc3.checkbox("Include biometric trend", value=not active_record["health_metrics"].empty,
                                                disabled=active_record["health_metrics"].empty)

            generate_clicked = st.form_submit_button("📄 Generate Doctor Summary PDF", type="primary", use_container_width=True)

        if generate_clicked:
            with st.spinner("Compiling clinical handoff PDF..."):
                try:
                    pdf_buf = generate_doctor_pdf(
                        patient_name=st.session_state.active_patient,
                        record=active_record,
                        emergency_contact=st.session_state.emergency_contact,
                        language=st.session_state.app_language,
                        include_chat=include_chat,
                        include_reports=include_reports,
                        include_biometrics=include_biometrics,
                        doctor_name=doctor_name,
                        referring_note=referring_note,
                    )
                    st.session_state["_doctor_pdf_bytes"] = pdf_buf.getvalue()
                    st.session_state["_doctor_pdf_meta"] = {
                        "patient": st.session_state.active_patient,
                        "doctor_email": doctor_email,
                        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
                    }
                    st.success("✅ Summary ready below.")
                except Exception as exc:
                    logger.error("PDF generation failed: %s", exc)
                    st.error(f"⚠️ Couldn't generate the PDF: {exc}")

        if st.session_state.get("_doctor_pdf_bytes") and st.session_state.get("_doctor_pdf_meta", {}).get("patient") == st.session_state.active_patient:
            meta = st.session_state["_doctor_pdf_meta"]
            st.download_button(
                "📥 Download Doctor Summary PDF",
                data=st.session_state["_doctor_pdf_bytes"],
                file_name=f"mediscan_handoff_{st.session_state.active_patient.replace(' ', '_')}_{date.today().isoformat()}.pdf",
                mime="application/pdf", use_container_width=True,
            )
            if meta.get("doctor_email"):
                if st.button(f"✉️ Mark as sent to {meta['doctor_email']}", use_container_width=True):
                    fire_emergency_webhook({
                        "alert": "doctor_handoff_shared",
                        "patient": meta["patient"],
                        "doctor_email": meta["doctor_email"],
                        "timestamp": datetime.now().isoformat(),
                    })
                    st.info(
                        f"📨 In a production deployment this would email the PDF to **{meta['doctor_email']}** "
                        "via a secure clinical messaging integration. For this prototype, download and share it manually.",
                        icon="ℹ️",
                    )

# ── Tab 2: Medical Report Interpreter ─────────────────────────────────────────
with tab2:
    st.markdown("## 📄 Medical Report Interpreter")
    st.info(
        "Capture or upload a **medical report, lab panel, or symptom photo** for instant "
        "AI-powered analysis with biomarker extraction and abnormality flagging.",
        icon="🔬",
    )

    if st.session_state.camera_active:
        camera_image = st.camera_input("Capture Symptom or Medical Report", facing_mode="environment")
        if st.button("🔌 Turn Off Camera", key="deactivate_camera", use_container_width=True):
            st.session_state.camera_active = False
            st.rerun()
    else:
        camera_image = None
        if st.button("📷 Open Camera to Capture Scan", key="activate_camera", use_container_width=True,
                      disabled=not _api_ready):
            st.session_state.camera_active = True
            st.rerun()

    st.markdown("**Or upload existing image(s):**")
    uploaded_files = st.file_uploader(
        "Upload from device", type=["png", "jpg", "jpeg"],
        help="Accepted formats: PNG, JPG, JPEG. You may select multiple files.",
        key="report_uploader", accept_multiple_files=True, disabled=not _api_ready,
    )

    image_sources = []
    if camera_image is not None:
        image_sources.append(("Camera capture", camera_image))
    if uploaded_files:
        image_sources.extend([(f.name, f) for f in uploaded_files])

    if image_sources:
        with st.expander("🖼️ Image Preview", expanded=False):
            preview_cols = st.columns(min(len(image_sources), 4))
            for i, (fname, fobj) in enumerate(image_sources):
                preview_cols[i % 4].image(fobj, caption=fname, use_container_width=True)

        # DESIGN NOTE: Analyze button outside form — triggers analysis immediately on click.
        if st.button("🔍 Analyze Image(s)", key="analyze_report", type="primary", use_container_width=True):
            lang_vision_instruction = VISION_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your entire analysis and the CDSCO disclaimer in {st.session_state.app_language}."
            # Build patient context for contextually-aware vision analysis
            vision_context_parts: list[str] = []
            prof = active_record["profile"]
            vision_context_parts.append(
                f"PATIENT CONTEXT: Age {prof.get('age', '?')}, Sex {prof.get('sex', '?')}, "
                f"Weight {prof.get('weight_kg', '?')} kg, Conditions: {prof.get('chronic_conditions') or 'None'}"
            )
            recent_msgs = active_record["chat_history"][-3:]
            if recent_msgs:
                vision_context_parts.append("RECENT SYMPTOM TRIAGE CONTEXT:")
                for msg in recent_msgs:
                    role = "Patient" if msg["role"] == "user" else "AI"
                    vision_context_parts.append(f"  {role}: {msg['content'][:200]}")
            context_text = "\n".join(vision_context_parts)
            for fname, fobj in image_sources:
                with st.spinner(f"Analyzing {fname} in {st.session_state.app_language}..."):
                    try:
                        pil_image = Image.open(fobj)
                        response = client.models.generate_content(
                            model="gemini-2.0-flash",
                            contents=[context_text, "Please analyze this medical image.", pil_image],
                            config=types.GenerateContentConfig(system_instruction=lang_vision_instruction),
                        )
                        result_text = response.text
                    except Exception as exc:
                        logger.error("Gemini vision analysis failed for %s: %s", fname, exc)
                        result_text = f"⚠️ **Gemini API error:** `{exc}`"
                    active_record["report_history"].append({
                        "id": uuid.uuid4().hex,
                        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
                        "filename": fname,
                        "result": result_text,
                    })
            st.rerun()

    if active_record["report_history"]:
        st.markdown("---")
        st.markdown(f"### 🗂️ Report History ({len(active_record['report_history'])})")
        for i, r in enumerate(reversed(active_record["report_history"])):
            # Deletion/second-opinion actions reference the report by its stable
            # uuid (assigned at creation) rather than by list position, so a
            # click can never land on the wrong entry even if the underlying
            # list is mutated between renders.
            report_id = r.get("id") or uuid.uuid4().hex
            with st.expander(f"👁️ {r['filename']} — {r['timestamp']}", expanded=(i == 0)):
                st.markdown(r["result"])
                bc1, bc2 = st.columns(2)
                if bc1.button("⚖️ Second Opinion (Groq Llama 3)", key=f"second_opinion_{report_id}",
                              use_container_width=True, disabled=groq_client is None):
                    with st.spinner("Consulting Groq Llama 3 Synthesizer..."):
                        try:
                            second_opinion = groq_client.chat.completions.create(
                                model="openai/gpt-oss-20b",
                                messages=[
                                    {"role": "system", "content": "You are a Senior Medical Synthesizer. Review the primary AI's OCR report analysis. Provide a brief second opinion, highlight any missed nuances, and give a final unified consensus."},
                                    {"role": "user", "content": f"Primary Analysis:\n{r['result']}"},
                                ],
                            )
                            st.info(second_opinion.choices[0].message.content, icon="🤖")
                        except Exception as exc:
                            logger.error("Groq second-opinion call failed: %s", exc)
                            st.error(f"Error generating second opinion: {exc}")
                if bc2.button("🗑️ Delete This Report", key=f"delete_report_{report_id}", use_container_width=True):
                    active_record["report_history"] = [
                        item for item in active_record["report_history"]
                        if item.get("id") != report_id
                    ]
                    st.rerun()
    else:
        st.caption("👆 Use the camera above or upload file(s) to begin analysis.")

# ── Tab 3: Health Dashboard ────────────────────────────────────────────────────
with tab3:
    st.markdown("## 📊 Health Dashboard")
    st.info(
        "Edit your 6-month biometric data below, explore predictive trend charts, "
        "and generate AI-powered preventative wellness insights.",
        icon="🫀",
    )

    # ── KPI Summary Row ──────────────────────────────────────────────────────────
    kpi1, kpi2, kpi3 = st.columns(3)
    _latest_risk = active_record["health_metrics"].iloc[-1]["Health_Risk_Score"]
    _prev_risk = active_record["health_metrics"].iloc[-2]["Health_Risk_Score"]
    kpi1.metric("📊 Overall Risk Trend", f"{int(_latest_risk)} / 100",
                delta=int(_latest_risk - _prev_risk), delta_color="inverse")
    if active_record["archived_conversations"]:
        _last_ts = active_record["archived_conversations"][-1]["timestamp"]
        _days = (date.today() - datetime.strptime(_last_ts, "%Y-%m-%d %H:%M").date()).days
        kpi2.metric("📅 Days Since Last Check-in", f"{_days} day{'s' if _days != 1 else ''}")
    elif active_record["chat_history"]:
        kpi2.metric("📅 Days Since Last Check-in", "Active now")
    else:
        kpi2.metric("📅 Days Since Last Check-in", "No sessions yet")
    _today_str = date.today().isoformat()
    _due = sum(1 for r in st.session_state.reminders
               if r["patient"] == st.session_state.active_patient and not r["done"] and r["date"] <= _today_str)
    _total_pending = sum(1 for r in st.session_state.reminders
                         if r["patient"] == st.session_state.active_patient and not r["done"])
    kpi3.metric("📌 Active Reminders Due",
                f"{_due} overdue" if _due else f"{_total_pending} pending",
                delta=f"-{_due} overdue" if _due else None,
                delta_color="inverse" if _due else "off")
    st.divider()

    @st.fragment(run_every=2)
    def render_telemetry():
        active_record = st.session_state.patients[st.session_state.active_patient]

        def toggle_telemetry():
            st.session_state.telemetry_active = not st.session_state.get("telemetry_active", False)
            if st.session_state.telemetry_active and "telemetry_history" not in st.session_state:
                st.session_state.telemetry_history = [
                    {"Reading": 1, "Heart_Rate": 72, "SpO2": 98, "HRV": 58},
                    {"Reading": 2, "Heart_Rate": 74, "SpO2": 97, "HRV": 56},
                    {"Reading": 3, "Heart_Rate": 73, "SpO2": 98, "HRV": 60},
                    {"Reading": 4, "Heart_Rate": 75, "SpO2": 97, "HRV": 55},
                    {"Reading": 5, "Heart_Rate": 76, "SpO2": 98, "HRV": 54},
                ]

        st.caption("🧪 **Simulated demo data** — not connected to a real wearable device.")
        st.button(
            "🔴 Stop Live Monitor" if st.session_state.get("telemetry_active", False) else "🟢 Start Live Monitor (Simulated Demo)",
            on_click=toggle_telemetry,
            type="primary" if not st.session_state.get("telemetry_active", False) else "secondary",
            key="telemetry_toggle_btn_unique"
        )

        if not st.session_state.get("telemetry_active", False):
            st.caption("⏸️ Simulated telemetry stream is currently paused. Click above to start a continuous 2-second demo biometric stream.")
            return

        if "telemetry_history" not in st.session_state or not st.session_state.telemetry_history:
            st.session_state.telemetry_history = [
                {"Reading": 1, "Heart_Rate": 72, "SpO2": 98, "HRV": 58},
                {"Reading": 2, "Heart_Rate": 74, "SpO2": 97, "HRV": 56},
                {"Reading": 3, "Heart_Rate": 73, "SpO2": 98, "HRV": 60},
                {"Reading": 4, "Heart_Rate": 75, "SpO2": 97, "HRV": 55},
                {"Reading": 5, "Heart_Rate": 76, "SpO2": 98, "HRV": 54},
            ]

        # Generate smooth continuous demo variations (simulated smartwatch sensor stream)
        last_hr = st.session_state.telemetry_history[-1]["Heart_Rate"]
        last_spo2 = st.session_state.telemetry_history[-1]["SpO2"]
        last_hrv = st.session_state.telemetry_history[-1]["HRV"]

        current_hr = int(np.clip(last_hr + np.random.randint(-3, 4), 58, 115))
        current_bp_systolic = int(np.clip(120 + (current_hr - 72) * 0.4 + np.random.randint(-3, 4), 100, 155))
        current_bp_diastolic = int(np.clip(78 + (current_hr - 72) * 0.2 + np.random.randint(-2, 3), 65, 95))
        current_ecg = "Normal Sinus Rhythm" if current_hr < 100 else "Sinus Tachycardia"
        if np.random.rand() < 0.05:
            current_ecg = "Irregular Rhythm (AFib Alert)"
        current_afib = "No AFib Detected" if "AFib" not in current_ecg else "Possible AFib Detected"
        current_spo2 = int(np.clip(last_spo2 + np.random.choice([-1, 0, 0, 1]), 89, 100))
        current_resp_rate = int(np.clip(14 + (current_hr - 72) // 8 + np.random.randint(-1, 2), 10, 24))
        current_sleep = "7h 12m (Deep: 1.5h, REM: 2.1h)"
        current_hrv = int(np.clip(last_hrv + np.random.randint(-4, 5), 20, 90))
        current_temp_dev = f"{np.random.uniform(-0.3, 0.4):+.1f} °C"
        current_fall = "No Fall Detected" if np.random.rand() > 0.02 else "⚠️ HARD FALL DETECTED! (simulated)"
        current_stress = int(np.clip(25 + (current_hr - 65) * 0.8 + np.random.randint(-4, 5), 5, 95))
        current_calories = 176 + len(st.session_state.telemetry_history) * 2

        next_reading_num = st.session_state.telemetry_history[-1]["Reading"] + 1
        st.session_state.telemetry_history.append({
            "Reading": next_reading_num,
            "Heart_Rate": current_hr, "SpO2": current_spo2, "HRV": current_hrv,
        })
        if len(st.session_state.telemetry_history) > 15:
            st.session_state.telemetry_history.pop(0)

        hist_df = pd.DataFrame(st.session_state.telemetry_history)

        st.markdown("#### 💓 Cardiovascular Metrics *(Simulated Stream)*")
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Pulse (HR)", f"{current_hr} bpm", delta=f"{current_hr - 72:+d} bpm")
        m2.metric("Blood Pressure (BP)", f"{current_bp_systolic}/{current_bp_diastolic} mmHg")
        m3.metric("ECG / EKG", current_ecg)
        m4.metric("AFib Check", current_afib)

        st.markdown("#### 🫁 Respiratory & Blood Metrics")
        r1, r2 = st.columns(2)
        r1.metric("Blood Oxygen (SpO2)", f"{current_spo2}%", delta=f"{current_spo2 - 95:+d}%")
        r2.metric("Respiratory Rate", f"{current_resp_rate} breaths/min", delta=f"{current_resp_rate - 14:+d}")

        st.markdown("#### 🛌 Sleep & Recovery")
        s1, s2, s3 = st.columns(3)
        s1.metric("Heart Rate Variability (HRV)", f"{current_hrv} ms", delta=f"{current_hrv - 50:+d} ms")
        s2.metric("Skin Temp Deviation", current_temp_dev)
        s3.metric("Sleep Quality Status", current_sleep)

        st.markdown("#### ⚠️ Specialized Safety & Exertion")
        d1, d2, d3 = st.columns(3)
        d1.metric("Fall/Seizure Guard", current_fall)
        d2.metric("Stress Level Score", f"{current_stress} / 100")
        d3.metric("Active Calories", f"{current_calories} kcal")

        if current_spo2 < 92:
            delivered = fire_emergency_webhook({"alert": "low_spo2", "value": int(current_spo2), "patient": st.session_state.active_patient})
            st.error(
                "🚨 **CRITICAL: SpO2 DROP DETECTED (simulated demo data)** 🚨\n\n"
                f"Simulated blood oxygen has fallen below 92%. {'Webhook notified.' if delivered else 'Webhook did not confirm delivery.'}"
            )

        fig, ax = plt.subplots(figsize=(7, 3))
        sns.lineplot(data=hist_df, x="Reading", y="Heart_Rate", label="Pulse (bpm)", ax=ax, color="#8884d8", marker="o", linewidth=2)
        sns.lineplot(data=hist_df, x="Reading", y="SpO2", label="SpO2 (%)", ax=ax, color="#ef4444", marker="s", linewidth=2)
        ax2 = ax.twinx()
        sns.lineplot(data=hist_df, x="Reading", y="HRV", label="HRV (ms)", ax2=ax2, color="blue", marker="s")
        ax.set_title("Simulated Live Pulse, SpO2, and HRV Telemetry (Demo Stream)", fontsize=11, fontweight="bold")
        ax.set_ylabel("Pulse (bpm) / SpO2 (%)", fontsize=9)
        ax2.set_ylabel("HRV (ms)", color="#3b82f6", fontsize=9)
        ax.legend(loc="upper left", fontsize=8)
        ax2.legend(loc="upper right", fontsize=8)
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    render_telemetry()
    st.divider()

    st.markdown("### 🗂️ Biometric Data Editor")
    st.caption("Edit any cell and click outside to apply. Changes are reflected live in the charts and flags below.")

    edited_df = st.data_editor(
        active_record["health_metrics"], use_container_width=True, hide_index=True,
        key=f"health_metrics_editor_{st.session_state.active_patient}",
        column_config={
            "Month": st.column_config.TextColumn("Month", disabled=True),
            "Resting_HR": st.column_config.NumberColumn("Resting HR (bpm)", min_value=40, max_value=200),
            "Systolic_BP": st.column_config.NumberColumn("Systolic BP (mmHg)", min_value=80, max_value=220),
            "Fasting_Glucose": st.column_config.NumberColumn("Fasting Glucose (mg/dL)", min_value=50, max_value=400),
            "Health_Risk_Score": st.column_config.NumberColumn("Health Risk Score (0–100)", min_value=0, max_value=100),
        },
    )
    active_record["health_metrics"] = edited_df
    df = edited_df

    st.divider()
    st.markdown("### 📍 Latest Readings")
    latest = df.iloc[-1]
    prev = df.iloc[-2]

    col1, col2, col3 = st.columns(3)
    for col, field, label, icon in [
        (col1, "Health_Risk_Score", "Health Risk Score", "⚠️"),
        (col2, "Resting_HR", "Resting HR", "💓"),
        (col3, "Fasting_Glucose", "Fasting Glucose", "🩸"),
    ]:
        flag_label, flag_color = metric_flag(field, latest[field])
        col.metric(
            label=f"{icon} {label}", value=f"{int(latest[field])}",
            delta=int(latest[field] - prev[field]), delta_color="inverse",
        )
        col.markdown(f":{flag_color}[{flag_label}]")

    if latest["Health_Risk_Score"] >= 85:
        delivered = fire_emergency_webhook({"alert": "high_risk_score", "score": int(latest["Health_Risk_Score"]), "patient": st.session_state.active_patient})
        st.error(
            "🚨 **CRITICAL RISK THRESHOLD EXCEEDED** 🚨\n\nScore is >= 85. "
            f"{'Preventative webhook notified.' if delivered else 'Webhook did not confirm delivery.'}"
        )

    st.divider()
    st.markdown("### 📈 Health Risk Score — 6-Month Trajectory")
    chart_df = df.set_index("Month")
    st.line_chart(chart_df[["Health_Risk_Score"]], height=300, use_container_width=True)

    with st.expander("📊 View All Biometric Trend Charts", expanded=False):
        ca, cb = st.columns(2)
        with ca:
            st.markdown("**💓 Resting HR (bpm)**")
            st.line_chart(chart_df[["Resting_HR"]], height=200)
        with cb:
            st.markdown("**🩸 Fasting Glucose (mg/dL)**")
            st.line_chart(chart_df[["Fasting_Glucose"]], height=200)
        st.markdown("**🩺 Systolic BP (mmHg)**")
        st.line_chart(chart_df[["Systolic_BP"]], height=200)

    st.divider()
    st.markdown("### 🤖 AI Preventative Health Coach")
    st.caption("Click below to pass your current biometric data to the AI for a personalised 3-point preventative wellness analysis.")

    # DESIGN NOTE: Health Coach button outside form — fires Gemini immediately on click.
    if st.button("✨ Generate AI Health Insight", key="generate_coach", type="primary",
                  use_container_width=True, disabled=not _api_ready):
        csv_string = df.to_csv(index=False)
        coach_prompt = (
            f"Here is the patient's 6-month biometric data in CSV format:\n\n{csv_string}\n\n"
            "Please analyse the month-over-month trajectory and provide your 3-bullet-point wellness recommendations."
        )
        with st.spinner(f"🧠 Health Coach is analysing your biometric trends in {st.session_state.app_language}..."):
            try:
                lang_coach_instruction = HEALTH_COACH_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your 3-bullet-point wellness recommendation and the CDSCO disclaimer entirely in {st.session_state.app_language}."
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=coach_prompt,
                    config=types.GenerateContentConfig(system_instruction=lang_coach_instruction),
                )
                active_record["coach_recommendation"] = response.text
            except Exception as exc:
                logger.error("Gemini health coach call failed: %s", exc)
                active_record["coach_recommendation"] = f"⚠️ **Gemini API error:** `{exc}`"

    if active_record["coach_recommendation"]:
        st.markdown("---")
        st.markdown("#### 📝 Wellness Recommendations")
        st.markdown(active_record["coach_recommendation"])
        if st.button("🗑️ Clear Recommendations", key="clear_coach"):
            active_record["coach_recommendation"] = None
            st.rerun()

# ── Tab 4: Reminders & Care Plan ──────────────────────────────────────────────
with tab4:
    st.markdown("## 🗓️ Reminders & Care Plan")
    st.info("Track upcoming appointments, medication refills, or follow-up tests for this patient.", icon="📌")

    with st.form("add_reminder_form", clear_on_submit=True):
        rc1, rc2 = st.columns([1, 2])
        r_date = rc1.date_input("Date", value=date.today())
        r_note = rc2.text_input("Reminder note", placeholder="e.g. Follow-up blood panel, Refill prescription...")
        if st.form_submit_button("➕ Add Reminder", use_container_width=True):
            if r_note.strip():
                st.session_state.reminders.append({
                    "id": uuid.uuid4().hex,
                    "patient": st.session_state.active_patient,
                    "date": r_date.isoformat(),
                    "note": r_note.strip(),
                    "done": False,
                })
                st.rerun()

    patient_reminders = [
        r for r in st.session_state.reminders
        if r["patient"] == st.session_state.active_patient
    ]
    patient_reminders.sort(key=lambda r: r["date"])

    if not patient_reminders:
        st.caption("No reminders yet for this patient.")
    else:
        today_str = date.today().isoformat()
        for r in patient_reminders:
            # Each reminder carries a stable uuid assigned at creation, so
            # toggle/delete actions target it directly instead of relying on
            # its position in st.session_state.reminders. This keeps the
            # buttons correct even if the underlying list is resorted,
            # filtered, or mutated by another action between reruns.
            rid = r["id"]
            overdue = (not r["done"]) and r["date"] < today_str
            row = st.columns([1, 4, 1, 1])
            row[0].markdown(f"{'🔴' if overdue else '🟢' if r['done'] else '🟡'} **{r['date']}**")
            row[1].markdown(f"~~{r['note']}~~" if r["done"] else r["note"])
            if row[2].button("✔️" if not r["done"] else "↩️", key=f"toggle_reminder_{rid}"):
                for item in st.session_state.reminders:
                    if item["id"] == rid:
                        item["done"] = not item["done"]
                        break
                st.rerun()
            if row[3].button("🗑️", key=f"delete_reminder_{rid}"):
                st.session_state.reminders = [
                    item for item in st.session_state.reminders if item["id"] != rid
                ]
                st.rerun()
