import streamlit as st
import pandas as pd
from PIL import Image
from google import genai
from google.genai import types
from groq import Groq
import requests
from gtts import gTTS
import io
import numpy as np
import tempfile
import os
import cv2
from ultralytics import YOLO
import mediapipe as mp

# Function to calculate interior angle between three joints
def calculate_angle(a, b, c):
    a = np.array(a)  # Shoulder
    b = np.array(b)  # Elbow
    c = np.array(c)  # Wrist
    
    radians = np.arctan2(c[1] - b[1], c[0] - b[0]) - np.arctan2(a[1] - b[1], a[0] - b[0])
    angle = np.abs(radians * 180.0 / np.pi)
    
    if angle > 180.0:
        angle = 360.0 - angle
        
    return angle



# ── Page Configuration ───────────────────────────────────────────────────────
st.set_page_config(
    page_title="MediScan AI",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Google GenAI Client ───────────────────────────────────────────────────────
try:
    client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
    _api_ready = True
except Exception:
    client = None
    _api_ready = False

# ── Groq Client ───────────────────────────────────────────────────────────────
try:
    groq_key = st.secrets.get("GROQ_API_KEY")
    groq_client = Groq(api_key=groq_key) if groq_key else None
except Exception:
    groq_client = None

# ── Triage System Instruction ─────────────────────────────────────────────────
TRIAGE_SYSTEM_INSTRUCTION = """
You are the MediScan AI Triage Assistant, an intelligent clinical first-filter system designed for use in resource-constrained medical environments. Your primary objective is to analyze chaotic patient-reported symptoms, cross-reference them with the provided patient demographic profile, and output a probabilistically ranked differential diagnosis.

OPERATIONAL CONSTRAINTS:
1. You are a triage assistant, NOT a prescribing physician. You must NEVER prescribe medications or suggest specific pharmacological dosages.
2. You must strictly limit your analysis to the top 3 most probable underlying conditions based on the provided symptoms and biometric baseline.
3. Your tone must remain highly clinical, empathetic, and objective.
4. You must format your response with clear markdown headings, bullet points for symptoms matched, and a distinct "Recommended Next Steps" section (e.g., "Schedule routine blood panel", "Visit urgent care").

MANDATORY DISCLAIMER:
You must append the following exact text to the very bottom of every single response you generate, with no exceptions:

"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Vision System Instruction ─────────────────────────────────────────────────
VISION_SYSTEM_INSTRUCTION = """
You are the MediScan AI Diagnostic Vision System, an advanced optical character recognition (OCR) and visual analysis engine. Your objective is to extract, structure, and analyze clinical data from uploaded medical documents (e.g., blood panels, pathology reports) or analyze physical symptom images (e.g., dermatological lesions).

OPERATIONAL CONSTRAINTS:
1. If the image is a document, meticulously extract key biomarkers and present them in a structured markdown table comparing extracted values against standard healthy reference ranges.
2. If the image is a document, you must also provide a detailed analysis of each term/biomarker, explaining:
   - What the term means in plain language.
   - Its health impact (clinical implications of standard, elevated, or low values).
   - How to tackle and manage it (dietary changes, lifestyle adjustments, preventative measures, or recommended follow-up tests).
3. If the image is a physical symptom, provide an objective visual description and list up to 3 potential differential diagnoses.
4. Flag any critical abnormalities or out-of-range metrics clearly.
5. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Health Coach System Instruction ──────────────────────────────────────────────
HEALTH_COACH_SYSTEM_INSTRUCTION = """
You are the MediScan AI Preventative Health Coach. You will be provided with a CSV string containing a patient's simulated 6-month biometric data, including Resting Heart Rate, Systolic Blood Pressure, Fasting Glucose, and a computed Health Risk Score.

OPERATIONAL CONSTRAINTS:
1. Analyze the month-over-month trajectory of the metrics. 
2. Provide a concise, 3-bullet-point wellness recommendation based STRICTLY on the trends in the data.
3. Emphasize preventative care and lifestyle modifications.
4. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Session State Initialization ──────────────────────────────────────────────
if "patient_profile" not in st.session_state:
    st.session_state.patient_profile = {
        "age": None,
        "sex": None,
        "weight": None,
        "chronic_conditions": "",
    }

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "report_result" not in st.session_state:
    st.session_state.report_result = None

if "coach_recommendation" not in st.session_state:
    st.session_state.coach_recommendation = None

if "kinetic_routine" not in st.session_state:
    st.session_state.kinetic_routine = None

if "kinetic_vision_result" not in st.session_state:
    st.session_state.kinetic_vision_result = None



if "health_metrics" not in st.session_state:
    st.session_state.health_metrics = pd.DataFrame()

if "camera_active" not in st.session_state:
    st.session_state.camera_active = False

if "app_language" not in st.session_state:
    st.session_state.app_language = "English"



# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🌐 Language Preferences")
    st.session_state.app_language = st.selectbox(
        "Select Response Language",
        ["English", "Hindi (हिन्दी)", "Marathi (मराठी)", "Bengali (বাংলা)", "Spanish (Español)"]
    )

    st.markdown("## 👤 Patient Profile")


    if not _api_ready:
        st.warning(
            "⚠️ **API key not configured.**\n\n"
            "Add your key to `.streamlit/secrets.toml`:\n"
            "```toml\nGEMINI_API_KEY = \"your-key-here\"\n```",
            icon="🔑",
        )

    if groq_client is None:
        st.warning(
            "⚠️ **Groq API key not configured.**\n\n"
            "Add your key to `.streamlit/secrets.toml`:\n"
            "```toml\nGROQ_API_KEY = \"your-key-here\"\n```",
            icon="🔑",
        )

    st.markdown("---")

    with st.form(key="patient_profile_form", clear_on_submit=False):
        age = st.number_input(
            "Age",
            min_value=0,
            max_value=120,
            value=st.session_state.patient_profile.get("age") or 25,
            step=1,
            help="Enter patient age in years",
        )

        sex = st.selectbox(
            "Sex",
            options=["Male", "Female", "Other", "Prefer not to say"],
            index=(
                ["Male", "Female", "Other", "Prefer not to say"].index(
                    st.session_state.patient_profile.get("sex") or "Male"
                )
            ),
        )

        weight = st.number_input(
            "Weight (kg)",
            min_value=0.0,
            max_value=500.0,
            value=float(st.session_state.patient_profile.get("weight") or 70.0),
            step=0.5,
            format="%.1f",
            help="Enter patient weight in kilograms",
        )

        chronic_conditions = st.text_area(
            "Chronic Conditions",
            value=st.session_state.patient_profile.get("chronic_conditions") or "",
            placeholder="e.g., Diabetes Type 2, Hypertension, Asthma...",
            height=100,
            help="List any pre-existing or chronic medical conditions",
        )

        submitted = st.form_submit_button(
            "💾 Save Profile",
            use_container_width=True,
            type="primary",
        )

        if submitted:
            st.session_state.patient_profile = {
                "age": age,
                "sex": sex,
                "weight": weight,
                "chronic_conditions": chronic_conditions,
            }
            st.success("✅ Profile saved!")

    # Display saved profile summary
    profile = st.session_state.patient_profile
    if profile.get("age"):
        st.markdown("---")
        st.markdown("### 📋 Current Profile")
        st.markdown(f"- **Age:** {profile['age']} yrs")
        st.markdown(f"- **Sex:** {profile['sex']}")
        st.markdown(f"- **Weight:** {profile['weight']} kg")
        if profile.get("chronic_conditions"):
            st.markdown(f"- **Conditions:** {profile['chronic_conditions']}")

    st.markdown("---")
    st.markdown("### 📄 Export Dossier")

    def generate_dossier():
        content = f"=== MEDISCAN AI PATIENT DOSSIER ===\n\n"
        content += f"PROFILE:\nAge: {profile.get('age')}\nSex: {profile.get('sex')}\nWeight: {profile.get('weight')} kg\nConditions: {profile.get('chronic_conditions')}\n\n"
        
        if not st.session_state.health_metrics.empty:
            content += f"BIOMETRIC TRAJECTORY (Last 6 Months):\n{st.session_state.health_metrics.to_string(index=False)}\n\n"
            
        if st.session_state.report_result:
            content += f"LATEST LAB REPORT ANALYSIS:\n{st.session_state.report_result}\n\n"
            
        return content

    st.download_button(
        label="📥 Download Clinical Dossier",
        data=generate_dossier(),
        file_name="mediscan_dossier.txt",
        mime="text/plain",
        use_container_width=True,
        type="secondary"
    )

# ── Main Content ──────────────────────────────────────────────────────────────
st.markdown("# 🩺 MediScan AI")
st.markdown("*Your intelligent medical assistant powered by Google Gemini*")
st.markdown("---")

tab1, tab2, tab3, tab4 = st.tabs([
    "🔬 Symptom Analyzer",
    "📄 Medical Report Interpreter",
    "📊 Health Dashboard",
    "🏃 AI Kinetic Coach",
])

# ── Tab 1: Symptom Analyzer ───────────────────────────────────────────────────
with tab1:
    st.markdown("## 🔬 Symptom Analyzer")
    st.info(
        "Describe your symptoms via text or voice. The AI will analyze them against "
        "your patient profile and return a ranked differential diagnosis.",
        icon="ℹ️",
    )

    # ── Render Chat History ───────────────────────────────────────────────────
    for message in st.session_state.chat_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # ── Audio Input ───────────────────────────────────────────────────────────
    st.markdown("#### 🎙️ Voice Input *(optional)*")
    audio_value = st.audio_input(
        "Record your symptoms",
        key="symptom_audio",
        help="Record a voice description of your symptoms alongside your text input.",
    )

    # ── Text Chat Input ───────────────────────────────────────────────────────
    user_text = st.chat_input(
        "Describe your symptoms here (e.g. fever for 3 days, severe headache, nausea)…"
    )

    # ── Handle Submission ─────────────────────────────────────────────────────
    import hashlib

    is_new_audio = False
    audio_hash = None
    if audio_value:
        try:
            audio_bytes = audio_value.getvalue()
            audio_hash = hashlib.md5(audio_bytes).hexdigest()
            if "last_processed_audio_hash" not in st.session_state or st.session_state.last_processed_audio_hash != audio_hash:
                is_new_audio = True
        except Exception:
            pass

    if user_text or is_new_audio:
        profile = st.session_state.patient_profile

        # Dynamic system instruction that includes the latest patient profile context
        dynamic_system_instruction = f"""{TRIAGE_SYSTEM_INSTRUCTION}

PATIENT BIOMETRIC BASELINE:
- Age: {profile.get('age', 'Not provided')} years
- Sex: {profile.get('sex', 'Not provided')}
- Weight: {profile.get('weight', 'Not provided')} kg
- Chronic Conditions: {profile.get('chronic_conditions') or 'None reported'}

CRITICAL LANGUAGE INSTRUCTION:
You must translate your entire response, including the differential diagnosis and recommended steps, into {st.session_state.app_language}. Ensure medical terms are accurately translated or transliterated. The CDSCO disclaimer must also be translated into {st.session_state.app_language}.
"""

        final_symptom_text = user_text or ""

        # If audio_value is not None and is new, transcribe it using Groq Whisper
        if is_new_audio and audio_value is not None:
            with st.spinner("🎙️ Transcribing audio with Groq Whisper..."):
                try:
                    transcription = groq_client.audio.transcriptions.create(
                        file=("audio.wav", audio_value.read()),
                        model="whisper-large-v3-turbo"
                    )
                    if final_symptom_text:
                        final_symptom_text += f"\nVoice note: {transcription.text}"
                    else:
                        final_symptom_text = transcription.text
                except Exception as exc:
                    st.error(f"🎙️ Whisper transcription error: {exc}")

        # Display final_symptom_text in a st.chat_message("user") block and append it to st.session_state.chat_history (with role "user").
        if final_symptom_text.strip():
            with st.chat_message("user"):
                st.markdown(final_symptom_text)
            st.session_state.chat_history.append({"role": "user", "content": final_symptom_text})

            # Build a messages_payload list for the Groq chat completion.
            messages_payload = [{"role": "system", "content": dynamic_system_instruction}]
            for msg in st.session_state.chat_history:
                # Ensure role names map correctly to Groq's expected roles
                role = "assistant" if msg["role"] == "assistant" else "user"
                messages_payload.append({"role": role, "content": msg["content"]})

            # Wrap the API call in with st.spinner(f"🧠 Analysing symptoms in {st.session_state.app_language}..."):
            with st.chat_message("assistant"):
                with st.spinner(f"🧠 Analysing symptoms in {st.session_state.app_language}..."):
                    try:
                        response = groq_client.chat.completions.create(
                            model="openai/gpt-oss-20b",
                            messages=messages_payload
                        )
                        assistant_reply = response.choices[0].message.content
                    except Exception as exc:
                        assistant_reply = f"⚠️ **Error communicating with Groq:** `{exc}`"

            st.markdown(assistant_reply)

            lang_map = {"English": "en", "Hindi (हिन्दी)": "hi", "Marathi (मराठी)": "mr", "Bengali (বাংলা)": "bn", "Spanish (Español)": "es"}
            tts_lang = lang_map.get(st.session_state.app_language, "en")
            try:
                # Clean markdown syntax before speaking
                clean_text = assistant_reply.replace("*", "").replace("#", "")
                tts = gTTS(text=clean_text, lang=tts_lang, slow=False)
                audio_fp = io.BytesIO()
                tts.write_to_fp(audio_fp)
                audio_fp.seek(0)
                st.audio(audio_fp, format="audio/mp3")
            except Exception as e:
                st.warning("Audio synthesis is temporarily unavailable.")

            critical_keywords = ["urgent care", "emergency", "immediate", "hospital", "chest pain", "stroke"]
            if any(keyword in assistant_reply.lower() for keyword in critical_keywords):
                st.error("🚨 **CRITICAL TRIAGE ESCALATION** 🚨\n\nHigh-risk symptoms detected. An automated webhook payload has been triggered to notify medical dispatch.")
                try:
                    # Simulated n8n Webhook
                    requests.post("https://hook.us1.make.com/mock-emergency", json={"profile": profile, "alert": "critical_symptoms"}, timeout=2)
                except:
                    pass

        st.session_state.chat_history.append(
            {"role": "assistant", "content": assistant_reply}
        )
        if audio_hash:
            st.session_state.last_processed_audio_hash = audio_hash
        st.rerun()


    st.divider()
    st.markdown("### 🏥 Nearby Care Centers (Pune)")
    st.caption("Simulated local clinics based on current geographic coordinates.")
    # Generate mock clinic coordinates around Pune (Lat: 18.5204, Lon: 73.8567)
    map_data = pd.DataFrame(
        np.random.randn(5, 2) / [60, 60] + [18.5204, 73.8567],
        columns=['lat', 'lon']
    )
    st.map(map_data, zoom=11, use_container_width=True)

    # ── Clear History ─────────────────────────────────────────────────────────
    if st.session_state.chat_history:
        st.divider()
        if st.button("🗑️ Clear Chat History", key="clear_symptom_chat"):
            st.session_state.chat_history = []
            if "last_processed_audio_hash" in st.session_state:
                del st.session_state.last_processed_audio_hash
            st.rerun()

# ── Tab 2: Medical Report Interpreter ─────────────────────────────────────
with tab2:
    st.markdown("## 📄 Medical Report Interpreter")
    st.info(
        "Capture or upload a **medical report, lab panel, or symptom photo** for instant "
        "AI-powered analysis with biomarker extraction and abnormality flagging.",
        icon="🔬",
    )

    # ── Req 2: Camera input (primary) + file uploader (fallback) ──────────────────
    if st.session_state.camera_active:
        camera_image = st.camera_input("Capture Symptom or Medical Report", facing_mode="environment")
        if st.button("🔌 Turn Off Camera", key="deactivate_camera", use_container_width=True):
            st.session_state.camera_active = False
            st.rerun()
    else:
        camera_image = None
        if st.button("📷 Open Camera to Capture Scan", key="activate_camera", use_container_width=True):
            st.session_state.camera_active = True
            st.rerun()

    st.markdown("**Or upload an existing image:**")
    uploaded_file = st.file_uploader(
        "Upload from device",
        type=["png", "jpg", "jpeg"],
        help="Accepted formats: PNG, JPG, JPEG.",
        key="report_uploader",
    )

    # Resolve which source to use — camera takes priority
    image_source = camera_image if camera_image is not None else uploaded_file

    # ── Req 3-6: Spinner → PIL.Image.open → Gemini call → Expander result ────────
    if image_source is not None:
        # Preview the image the user provided
        with st.expander("🖴 Image Preview", expanded=False):
            st.image(image_source, use_container_width=True)

        if st.button(
            "🔍 Analyze Image",
            key="analyze_report",
            type="primary",
            use_container_width=True,
        ):
            # Req 4: Read into memory with PIL.Image.open()
            pil_image = Image.open(image_source)

            # Req 3: Spinner wraps all processing
            with st.spinner(f"Analyzing medical visual data in {st.session_state.app_language}..."):
                try:
                    lang_vision_instruction = VISION_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your entire analysis and the CDSCO disclaimer in {st.session_state.app_language}."
                    # Req 5: Pass text string + Pillow image object directly;
                    #         apply VISION_SYSTEM_INSTRUCTION via GenerateContentConfig
                    response = client.models.generate_content(
                        model="gemini-3.6-flash",
                        contents=["Please analyze this medical image.", pil_image],
                        config=types.GenerateContentConfig(
                            system_instruction=lang_vision_instruction,
                        ),
                    )
                    st.session_state.report_result = response.text
                except Exception as exc:
                    st.session_state.report_result = (
                        f"⚠️ **Gemini API error:** `{exc}`"
                    )

        if st.session_state.report_result:
            with st.expander("👁️ Primary Analysis (Gemini Vision)", expanded=True):
                st.markdown(st.session_state.report_result)
                
            st.markdown("---")
            st.markdown("#### ⚖️ Multi-Agent Cross-Verification")
            if st.button("Request Second Opinion (Groq Llama 3)", type="secondary", use_container_width=True):
                with st.spinner("Consulting Groq Llama 3 Synthesizer..."):
                    try:
                        second_opinion = groq_client.chat.completions.create(
                            model="openai/gpt-oss-20b",
                            messages=[
                                {"role": "system", "content": "You are a Senior Medical Synthesizer. Review the primary AI's OCR report analysis. Provide a brief second opinion, highlight any missed nuances, and give a final unified consensus."},
                                {"role": "user", "content": f"Primary Analysis:\n{st.session_state.report_result}"}
                            ]
                        )
                        st.info(second_opinion.choices[0].message.content, icon="🤖")
                    except Exception as exc:
                        st.error(f"Error generating second opinion: {exc}")

            if st.button("🗑️ Clear Analysis", key="clear_report"):
                st.session_state.report_result = None
                st.rerun()

    else:
        st.caption("👆 Use the camera above or upload a file to begin analysis.")


# ── Tab 3: Health Dashboard ─────────────────────────────────────────────────
with tab3:
    st.markdown("## 📊 Health Dashboard")
    st.info(
        "Edit your 6-month biometric data below, explore predictive trend charts, "
        "and generate AI-powered preventative wellness insights.",
        icon="🫀",
    )

    # ── Req 2: Initialize health_metrics with spec-compliant column names ──────
    if st.session_state.health_metrics.empty:
        st.session_state.health_metrics = pd.DataFrame({
            "Month":              ["March", "April", "May", "June", "July", "August"],
            "Resting_HR":         [72,  74,  73,  76,  78,  80],
            "Systolic_BP":        [118, 121, 119, 125, 128, 131],
            "Fasting_Glucose":    [92,  94,  96,  99,  101, 104],
            "Health_Risk_Score":  [18,  22,  20,  31,  38,  42],
        })

    # ── Req 3: Editable data table — writes changes back to session state ──────
    st.markdown("### 🗂️ Biometric Data Editor")
    st.caption("Edit any cell and click outside to apply. Changes are reflected live in the charts below.")

    edited_df = st.data_editor(
        st.session_state.health_metrics,
        use_container_width=True,
        hide_index=True,
        key="health_metrics_editor",
        column_config={
            "Month":             st.column_config.TextColumn("Month", disabled=True),
            "Resting_HR":        st.column_config.NumberColumn("Resting HR (bpm)",        min_value=40,  max_value=200),
            "Systolic_BP":       st.column_config.NumberColumn("Systolic BP (mmHg)",       min_value=80,  max_value=220),
            "Fasting_Glucose":   st.column_config.NumberColumn("Fasting Glucose (mg/dL)", min_value=50,  max_value=400),
            "Health_Risk_Score": st.column_config.NumberColumn("Health Risk Score (0–100)",min_value=0,   max_value=100),
        },
    )
    # Write edits back to session state immediately
    st.session_state.health_metrics = edited_df
    df = edited_df

    st.divider()

    # ── Req 4: st.columns(3) metric row ──────────────────────────────────────
    st.markdown("### 📍 Latest Readings")
    latest = df.iloc[-1]
    prev   = df.iloc[-2]

    risk_delta = int(latest["Health_Risk_Score"] - prev["Health_Risk_Score"])

    col1, col2, col3 = st.columns(3)

    # Column 1 — Health Risk Score with required delta + delta_color='inverse'
    col1.metric(
        label="⚠️ Health Risk Score",
        value=f"{int(latest['Health_Risk_Score'])} / 100",
        delta=risk_delta,
        delta_color="inverse",          # higher score = bad → red arrow up
    )
    col2.metric(
        label="💓 Resting HR",
        value=f"{int(latest['Resting_HR'])} bpm",
        delta=int(latest["Resting_HR"] - prev["Resting_HR"]),
        delta_color="inverse",
    )
    col3.metric(
        label="🩸 Fasting Glucose",
        value=f"{int(latest['Fasting_Glucose'])} mg/dL",
        delta=int(latest["Fasting_Glucose"] - prev["Fasting_Glucose"]),
        delta_color="inverse",
    )

    if latest["Health_Risk_Score"] >= 85:
        st.error("🚨 **CRITICAL RISK THRESHOLD EXCEEDED** 🚨\n\nScore is >= 85. Preventative automated webhook triggered to emergency contact.")
        try:
            requests.post("https://hook.us1.make.com/mock-emergency", json={"alert": "high_risk_score", "score": int(latest["Health_Risk_Score"])}, timeout=2)
        except:
            pass

    st.divider()

    # ── Req 5: Line chart — Health_Risk_Score (y) vs Month (x) ───────────────
    st.markdown("### 📈 Health Risk Score — 6-Month Trajectory")
    chart_df = df.set_index("Month")
    st.line_chart(
        chart_df[["Health_Risk_Score"]],
        height=300,
        use_container_width=True,
    )

    # Secondary supporting charts
    with st.expander("📊 View All Biometric Trend Charts", expanded=False):
        ca, cb = st.columns(2)
        with ca:
            st.markdown("**💓 Resting HR (bpm)**")
            st.line_chart(chart_df[["Resting_HR"]], height=200)
        with cb:
            st.markdown("**🩸 Fasting Glucose (mg/dL)**")
            st.line_chart(chart_df[["Fasting_Glucose"]], height=200)
        st.markdown("**🪀 Systolic BP (mmHg)**")
        st.line_chart(chart_df[["Systolic_BP"]], height=200)

    st.divider()

    # ── Req 6: AI Health Insight button ──────────────────────────────────────
    st.markdown("### 🤖 AI Preventative Health Coach")
    st.caption(
        "Click below to pass your current biometric data to Gemini for a "
        "personalised 3-point preventative wellness analysis."
    )

    if st.button(
        "✨ Generate AI Health Insight",
        key="generate_coach",
        type="primary",
        use_container_width=True,
    ):
        # Convert the live (possibly edited) DataFrame to a CSV string
        csv_string = df.to_csv(index=False)
        coach_prompt = (
            f"Here is the patient's 6-month biometric data in CSV format:\n\n"
            f"{csv_string}\n\n"
            "Please analyse the month-over-month trajectory and provide your "
            "3-bullet-point wellness recommendations."
        )

        with st.spinner(f"🧠 Health Coach is analysing your biometric trends in {st.session_state.app_language}..."):
            try:
                lang_coach_instruction = HEALTH_COACH_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your 3-bullet-point wellness recommendation and the CDSCO disclaimer entirely in {st.session_state.app_language}."
                response = groq_client.chat.completions.create(
                    model="openai/gpt-oss-20b",
                    messages=[
                        {"role": "system", "content": lang_coach_instruction},
                        {"role": "user", "content": coach_prompt}
                    ]
                )
                st.session_state.coach_recommendation = response.choices[0].message.content
            except Exception as exc:
                st.session_state.coach_recommendation = (
                    f"⚠️ **Groq API error:** `{exc}`"
                )

    # Display the AI response below the chart
    if st.session_state.coach_recommendation:
        st.markdown("---")
        st.markdown("#### 📝 Wellness Recommendations")
        st.markdown(st.session_state.coach_recommendation)
        if st.button("🗑️ Clear Recommendations", key="clear_coach"):
            st.session_state.coach_recommendation = None
            st.rerun()

# ── Tab 4: AI Kinetic Coach ───────────────────────────────────────────────────
with tab4:
    st.markdown("## 🏃 AI Kinetic Coach")
    st.info(
        "Get custom, age-appropriate physical exercise routines and perform posture biomechanics analysis.",
        icon="🏃",
    )

    # Requirement 2: Age-Based Recommendations
    if st.button("Generate Daily Routine", key="generate_kinetic_routine", type="primary", use_container_width=True):
        profile = st.session_state.patient_profile
        age = profile.get("age")
        conditions = profile.get("chronic_conditions") or "None reported"

        if not age:
            st.warning("⚠️ Please fill out the Patient Profile (specifically Age) in the sidebar to generate a suitable routine.")
        else:
            with st.spinner("🧠 Generating your custom exercise routine..."):
                try:
                    prompt = f"The patient is {age} years old with the following conditions: {conditions}. Recommend 3 daily exercises suitable for their demographic. Format with emojis and clear instructions."
                    
                    response = groq_client.chat.completions.create(
                        model="openai/gpt-oss-20b",
                        messages=[
                            {"role": "system", "content": "You are the MediScan AI Kinetic Coach, an expert fitness trainer and physical therapist. Provide highly safe, targeted, and age-appropriate physical exercise plans based on the patient's conditions. Always end your response with the CDSCO compliance disclaimer."},
                            {"role": "user", "content": prompt}
                        ]
                    )
                    st.session_state.kinetic_routine = response.choices[0].message.content
                except Exception as exc:
                    st.session_state.kinetic_routine = f"⚠️ **Groq API error:** `{exc}`"

    if st.session_state.kinetic_routine:
        st.markdown("---")
        st.markdown("#### 🏃 Recommended Exercise Routine")
        st.markdown(st.session_state.kinetic_routine)
        if st.button("🗑️ Clear Routine", key="clear_kinetic_routine"):
            st.session_state.kinetic_routine = None
            st.rerun()

    st.markdown("---")
    st.markdown("### 🏋️‍♂️ AI Gym Trainer (Bicep Curl Tracker)")
    
    uploaded_video = st.file_uploader(
        "Upload Bicep Curl Exercise Video",
        type=["mp4", "mov", "avi"],
        help="Upload a video of your bicep curls to analyze your reps and posture."
    )

    if uploaded_video is not None:
        st.info("📹 Video file loaded. Click the button below to start the AI Gym Trainer.")

        if st.button("🚀 Start AI Gym Trainer", key="start_gym_trainer", type="primary", use_container_width=True):
            try:
                # Save bytes to a temporary file
                with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_video:
                    temp_video.write(uploaded_video.read())
                    temp_video_path = temp_video.name

                st.markdown("### 📊 Real-Time Rep Counter & Form Tracker")
                frame_window = st.empty() # Placeholder for live video playback

                # Rep Counter State Variables
                counter = 0
                stage = None
                feedback = "Get in position"

                with st.spinner("Initializing MediaPipe Pose Landmarker..."):
                    mp_pose = mp.solutions.pose
                    # Initialize Pose landmarker
                    pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)
                    cap = cv2.VideoCapture(temp_video_path)
                    
                    while cap.isOpened():
                        ret, frame = cap.read()
                        if not ret:
                            break
                            
                        h, w, _ = frame.shape
                        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                        
                        # Process with MediaPipe
                        results = pose.process(rgb_frame)
                        
                        if results.pose_landmarks:
                            landmarks = results.pose_landmarks.landmark
                            
                            # Left Arm Keypoints: Shoulder (11), Elbow (13), Wrist (15)
                            shoulder = [landmarks[11].x * w, landmarks[11].y * h]
                            elbow    = [landmarks[13].x * w, landmarks[13].y * h]
                            wrist    = [landmarks[15].x * w, landmarks[15].y * h]
                            
                            # Calculate Elbow Angle
                            angle = calculate_angle(shoulder, elbow, wrist)
                            
                            # Rep Counting & Form Feedback Logic
                            if angle > 160:
                                stage = "Down"
                                feedback = "Good extension! Now curl up."
                            if angle < 30 and stage == 'Down':
                                stage = "Up"
                                counter += 1
                                feedback = "Rep completed!"
                            elif angle > 30 and angle < 90 and stage == "Down":
                                feedback = "Keep curling all the way up!"

                            # Draw Joint Overlay on Elbow
                            cv2.circle(frame, (int(elbow[0]), int(elbow[1])), 10, (0, 255, 255), -1)
                            cv2.putText(frame, f"{int(angle)} deg", (int(elbow[0]) + 15, int(elbow[1])),
                                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

                        # Render HUD Box
                        cv2.rectangle(frame, (0, 0), (320, 100), (245, 117, 16), -1)
                        
                        # Render Rep Counter
                        cv2.putText(frame, 'REPS', (15, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
                        cv2.putText(frame, str(counter), (15, 80), cv2.FONT_HERSHEY_SIMPLEX, 1.8, (255, 255, 255), 2)
                        
                        # Render Stage State
                        cv2.putText(frame, 'STAGE', (120, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
                        cv2.putText(frame, str(stage), (120, 80), cv2.FONT_HERSHEY_SIMPLEX, 1.8, (255, 255, 255), 2)

                        # Render Guidance Feedback
                        cv2.putText(frame, feedback, (10, h - 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

                        # Convert BGR to RGB for Streamlit and render live
                        rgb_output = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                        frame_window.image(rgb_output, channels="RGB")
                        
                    cap.release()
                    pose.close()

                # Clean up the temp file
                os.remove(temp_video_path)
                st.success(f"Workout finished! Total Reps: {counter}")
            except Exception as exc:
                st.error(f"⚠️ **Gym Trainer error:** `{exc}`")
                if 'temp_video_path' in locals() and os.path.exists(temp_video_path):
                    try:
                        os.remove(temp_video_path)
                    except Exception:
                        pass





import streamlit as st
import pandas as pd
from PIL import Image
from google import genai
from google.genai import types
from groq import Groq

# ── Page Configuration ───────────────────────────────────────────────────────
st.set_page_config(
    page_title="MediScan AI",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Google GenAI Client ───────────────────────────────────────────────────────
try:
    client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
    _api_ready = True
except Exception:
    client = None
    _api_ready = False

# ── Groq Client ───────────────────────────────────────────────────────────────
try:
    groq_key = st.secrets.get("GROQ_API_KEY")
    groq_client = Groq(api_key=groq_key) if groq_key else None
except Exception:
    groq_client = None

# ── Triage System Instruction ─────────────────────────────────────────────────
TRIAGE_SYSTEM_INSTRUCTION = """
You are the MediScan AI Triage Assistant, an intelligent clinical first-filter system designed for use in resource-constrained medical environments. Your primary objective is to analyze chaotic patient-reported symptoms, cross-reference them with the provided patient demographic profile, and output a probabilistically ranked differential diagnosis.

OPERATIONAL CONSTRAINTS:
1. You are a triage assistant, NOT a prescribing physician. You must NEVER prescribe medications or suggest specific pharmacological dosages.
2. You must strictly limit your analysis to the top 3 most probable underlying conditions based on the provided symptoms and biometric baseline.
3. Your tone must remain highly clinical, empathetic, and objective.
4. You must format your response with clear markdown headings, bullet points for symptoms matched, and a distinct "Recommended Next Steps" section (e.g., "Schedule routine blood panel", "Visit urgent care").

MANDATORY DISCLAIMER:
You must append the following exact text to the very bottom of every single response you generate, with no exceptions:

"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Vision System Instruction ─────────────────────────────────────────────────
VISION_SYSTEM_INSTRUCTION = """
You are the MediScan AI Diagnostic Vision System, an advanced optical character recognition (OCR) and visual analysis engine. Your objective is to extract, structure, and analyze clinical data from uploaded medical documents (e.g., blood panels, pathology reports) or analyze physical symptom images (e.g., dermatological lesions).

OPERATIONAL CONSTRAINTS:
1. If the image is a document, meticulously extract key biomarkers and present them in a structured markdown table comparing extracted values against standard healthy reference ranges.
2. If the image is a document, you must also provide a detailed analysis of each term/biomarker, explaining:
   - What the term means in plain language.
   - Its health impact (clinical implications of standard, elevated, or low values).
   - How to tackle and manage it (dietary changes, lifestyle adjustments, preventative measures, or recommended follow-up tests).
3. If the image is a physical symptom, provide an objective visual description and list up to 3 potential differential diagnoses.
4. Flag any critical abnormalities or out-of-range metrics clearly.
5. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Health Coach System Instruction ──────────────────────────────────────────────
HEALTH_COACH_SYSTEM_INSTRUCTION = """
You are the MediScan AI Preventative Health Coach. You will be provided with a CSV string containing a patient's simulated 6-month biometric data, including Resting Heart Rate, Systolic Blood Pressure, Fasting Glucose, and a computed Health Risk Score.

OPERATIONAL CONSTRAINTS:
1. Analyze the month-over-month trajectory of the metrics. 
2. Provide a concise, 3-bullet-point wellness recommendation based STRICTLY on the trends in the data.
3. Emphasize preventative care and lifestyle modifications.
4. You must append the following exact text to the very bottom of your response:
"***CDSCO COMPLIANCE DISCLAIMER:*** *MediScan AI is a Clinical Decision Support System (CDSS). The information provided is generated by an artificial intelligence model and is strictly for triage and informational purposes. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Immediate consultation with a registered medical practitioner is advised before making any health-related decisions.*"
"""

# ── Session State Initialization ──────────────────────────────────────────────
if "patient_profile" not in st.session_state:
    st.session_state.patient_profile = {
        "age": None,
        "sex": None,
        "weight": None,
        "chronic_conditions": "",
    }

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "report_result" not in st.session_state:
    st.session_state.report_result = None

if "coach_recommendation" not in st.session_state:
    st.session_state.coach_recommendation = None

if "health_metrics" not in st.session_state:
    st.session_state.health_metrics = pd.DataFrame()

if "camera_active" not in st.session_state:
    st.session_state.camera_active = False

if "app_language" not in st.session_state:
    st.session_state.app_language = "English"



# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🌐 Language Preferences")
    st.session_state.app_language = st.selectbox(
        "Select Response Language",
        ["English", "Hindi (हिन्दी)", "Marathi (मराठी)", "Bengali (বাংলা)", "Spanish (Español)"]
    )

    st.markdown("## 👤 Patient Profile")


    if not _api_ready:
        st.warning(
            "⚠️ **API key not configured.**\n\n"
            "Add your key to `.streamlit/secrets.toml`:\n"
            "```toml\nGEMINI_API_KEY = \"your-key-here\"\n```",
            icon="🔑",
        )

    if groq_client is None:
        st.warning(
            "⚠️ **Groq API key not configured.**\n\n"
            "Add your key to `.streamlit/secrets.toml`:\n"
            "```toml\nGROQ_API_KEY = \"your-key-here\"\n```",
            icon="🔑",
        )

    st.markdown("---")

    with st.form(key="patient_profile_form", clear_on_submit=False):
        age = st.number_input(
            "Age",
            min_value=0,
            max_value=120,
            value=st.session_state.patient_profile.get("age") or 25,
            step=1,
            help="Enter patient age in years",
        )

        sex = st.selectbox(
            "Sex",
            options=["Male", "Female", "Other", "Prefer not to say"],
            index=(
                ["Male", "Female", "Other", "Prefer not to say"].index(
                    st.session_state.patient_profile.get("sex") or "Male"
                )
            ),
        )

        weight = st.number_input(
            "Weight (kg)",
            min_value=0.0,
            max_value=500.0,
            value=float(st.session_state.patient_profile.get("weight") or 70.0),
            step=0.5,
            format="%.1f",
            help="Enter patient weight in kilograms",
        )

        chronic_conditions = st.text_area(
            "Chronic Conditions",
            value=st.session_state.patient_profile.get("chronic_conditions") or "",
            placeholder="e.g., Diabetes Type 2, Hypertension, Asthma...",
            height=100,
            help="List any pre-existing or chronic medical conditions",
        )

        submitted = st.form_submit_button(
            "💾 Save Profile",
            use_container_width=True,
            type="primary",
        )

        if submitted:
            st.session_state.patient_profile = {
                "age": age,
                "sex": sex,
                "weight": weight,
                "chronic_conditions": chronic_conditions,
            }
            st.success("✅ Profile saved!")

    # Display saved profile summary
    profile = st.session_state.patient_profile
    if profile.get("age"):
        st.markdown("---")
        st.markdown("### 📋 Current Profile")
        st.markdown(f"- **Age:** {profile['age']} yrs")
        st.markdown(f"- **Sex:** {profile['sex']}")
        st.markdown(f"- **Weight:** {profile['weight']} kg")
        if profile.get("chronic_conditions"):
            st.markdown(f"- **Conditions:** {profile['chronic_conditions']}")

# ── Main Content ──────────────────────────────────────────────────────────────
st.markdown("# 🩺 MediScan AI")
st.markdown("*Your intelligent medical assistant powered by Google Gemini*")
st.markdown("---")

tab1, tab2, tab3 = st.tabs([
    "🔬 Symptom Analyzer",
    "📄 Medical Report Interpreter",
    "📊 Health Dashboard",
])

# ── Tab 1: Symptom Analyzer ───────────────────────────────────────────────────
with tab1:
    st.markdown("## 🔬 Symptom Analyzer")
    st.info(
        "Describe your symptoms via text or voice. The AI will analyze them against "
        "your patient profile and return a ranked differential diagnosis.",
        icon="ℹ️",
    )

    # ── Render Chat History ───────────────────────────────────────────────────
    for message in st.session_state.chat_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # ── Audio Input ───────────────────────────────────────────────────────────
    st.markdown("#### 🎙️ Voice Input *(optional)*")
    audio_value = st.audio_input(
        "Record your symptoms",
        key="symptom_audio",
        help="Record a voice description of your symptoms alongside your text input.",
    )

    # ── Text Chat Input ───────────────────────────────────────────────────────
    user_text = st.chat_input(
        "Describe your symptoms here (e.g. fever for 3 days, severe headache, nausea)…"
    )

    # ── Handle Submission ─────────────────────────────────────────────────────
    import hashlib

    is_new_audio = False
    audio_hash = None
    if audio_value:
        try:
            audio_bytes = audio_value.getvalue()
            audio_hash = hashlib.md5(audio_bytes).hexdigest()
            if "last_processed_audio_hash" not in st.session_state or st.session_state.last_processed_audio_hash != audio_hash:
                is_new_audio = True
        except Exception:
            pass

    if user_text or is_new_audio:
        profile = st.session_state.patient_profile

        # Dynamic system instruction that includes the latest patient profile context
        dynamic_system_instruction = f"""{TRIAGE_SYSTEM_INSTRUCTION}

PATIENT BIOMETRIC BASELINE:
- Age: {profile.get('age', 'Not provided')} years
- Sex: {profile.get('sex', 'Not provided')}
- Weight: {profile.get('weight', 'Not provided')} kg
- Chronic Conditions: {profile.get('chronic_conditions') or 'None reported'}

CRITICAL LANGUAGE INSTRUCTION:
You must translate your entire response, including the differential diagnosis and recommended steps, into {st.session_state.app_language}. Ensure medical terms are accurately translated or transliterated. The CDSCO disclaimer must also be translated into {st.session_state.app_language}.
"""

        final_symptom_text = user_text or ""

        # If audio_value is not None and is new, transcribe it using Groq Whisper
        if is_new_audio and audio_value is not None:
            with st.spinner("🎙️ Transcribing audio with Groq Whisper..."):
                try:
                    transcription = groq_client.audio.transcriptions.create(
                        file=("audio.wav", audio_value.read()),
                        model="whisper-large-v3-turbo"
                    )
                    if final_symptom_text:
                        final_symptom_text += f"\nVoice note: {transcription.text}"
                    else:
                        final_symptom_text = transcription.text
                except Exception as exc:
                    st.error(f"🎙️ Whisper transcription error: {exc}")

        # Display final_symptom_text in a st.chat_message("user") block and append it to st.session_state.chat_history (with role "user").
        if final_symptom_text.strip():
            with st.chat_message("user"):
                st.markdown(final_symptom_text)
            st.session_state.chat_history.append({"role": "user", "content": final_symptom_text})

            # Build a messages_payload list for the Groq chat completion.
            messages_payload = [{"role": "system", "content": dynamic_system_instruction}]
            for msg in st.session_state.chat_history:
                # Ensure role names map correctly to Groq's expected roles
                role = "assistant" if msg["role"] == "assistant" else "user"
                messages_payload.append({"role": role, "content": msg["content"]})

            # Wrap the API call in with st.spinner(f"🧠 Analysing symptoms in {st.session_state.app_language}..."):
            with st.chat_message("assistant"):
                with st.spinner(f"🧠 Analysing symptoms in {st.session_state.app_language}..."):
                    try:
                        response = groq_client.chat.completions.create(
                            model="openai/gpt-oss-20b",
                            messages=messages_payload
                        )
                        assistant_reply = response.choices[0].message.content
                    except Exception as exc:
                        assistant_reply = f"⚠️ **Error communicating with Groq:** `{exc}`"

            st.markdown(assistant_reply)

        st.session_state.chat_history.append(
            {"role": "assistant", "content": assistant_reply}
        )
        if audio_hash:
            st.session_state.last_processed_audio_hash = audio_hash
        st.rerun()


    # ── Clear History ─────────────────────────────────────────────────────────
    if st.session_state.chat_history:
        st.divider()
        if st.button("🗑️ Clear Chat History", key="clear_symptom_chat"):
            st.session_state.chat_history = []
            if "last_processed_audio_hash" in st.session_state:
                del st.session_state.last_processed_audio_hash
            st.rerun()

# ── Tab 2: Medical Report Interpreter ─────────────────────────────────────
with tab2:
    st.markdown("## 📄 Medical Report Interpreter")
    st.info(
        "Capture or upload a **medical report, lab panel, or symptom photo** for instant "
        "AI-powered analysis with biomarker extraction and abnormality flagging.",
        icon="🔬",
    )

    # ── Req 2: Camera input (primary) + file uploader (fallback) ──────────────────
    if st.session_state.camera_active:
        camera_image = st.camera_input("Capture Symptom or Medical Report", facing_mode="environment")
        if st.button("🔌 Turn Off Camera", key="deactivate_camera", use_container_width=True):
            st.session_state.camera_active = False
            st.rerun()
    else:
        camera_image = None
        if st.button("📷 Open Camera to Capture Scan", key="activate_camera", use_container_width=True):
            st.session_state.camera_active = True
            st.rerun()

    st.markdown("**Or upload an existing image:**")
    uploaded_file = st.file_uploader(
        "Upload from device",
        type=["png", "jpg", "jpeg"],
        help="Accepted formats: PNG, JPG, JPEG.",
        key="report_uploader",
    )

    # Resolve which source to use — camera takes priority
    image_source = camera_image if camera_image is not None else uploaded_file

    # ── Req 3-6: Spinner → PIL.Image.open → Gemini call → Expander result ────────
    if image_source is not None:
        # Preview the image the user provided
        with st.expander("🖴 Image Preview", expanded=False):
            st.image(image_source, use_container_width=True)

        if st.button(
            "🔍 Analyze Image",
            key="analyze_report",
            type="primary",
            use_container_width=True,
        ):
            # Req 4: Read into memory with PIL.Image.open()
            pil_image = Image.open(image_source)

            # Req 3: Spinner wraps all processing
            with st.spinner(f"Analyzing medical visual data in {st.session_state.app_language}..."):
                try:
                    lang_vision_instruction = VISION_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your entire analysis and the CDSCO disclaimer in {st.session_state.app_language}."
                    # Req 5: Pass text string + Pillow image object directly;
                    #         apply VISION_SYSTEM_INSTRUCTION via GenerateContentConfig
                    response = client.models.generate_content(
                        model="gemini-3.6-flash",
                        contents=["Please analyze this medical image.", pil_image],
                        config=types.GenerateContentConfig(
                            system_instruction=lang_vision_instruction,
                        ),
                    )
                    st.session_state.report_result = response.text
                except Exception as exc:
                    st.session_state.report_result = (
                        f"⚠️ **Gemini API error:** `{exc}`"
                    )

        # Req 6: Render result inside an expander
        if st.session_state.report_result:
            with st.expander("View Diagnostic Analysis", expanded=True):
                st.markdown(st.session_state.report_result)

            if st.button("🗑️ Clear Analysis", key="clear_report"):
                st.session_state.report_result = None
                st.rerun()

    else:
        st.caption("👆 Use the camera above or upload a file to begin analysis.")


# ── Tab 3: Health Dashboard ─────────────────────────────────────────────────
with tab3:
    st.markdown("## 📊 Health Dashboard")
    st.info(
        "Edit your 6-month biometric data below, explore predictive trend charts, "
        "and generate AI-powered preventative wellness insights.",
        icon="🫀",
    )

    # ── Req 2: Initialize health_metrics with spec-compliant column names ──────
    if st.session_state.health_metrics.empty:
        st.session_state.health_metrics = pd.DataFrame({
            "Month":              ["March", "April", "May", "June", "July", "August"],
            "Resting_HR":         [72,  74,  73,  76,  78,  80],
            "Systolic_BP":        [118, 121, 119, 125, 128, 131],
            "Fasting_Glucose":    [92,  94,  96,  99,  101, 104],
            "Health_Risk_Score":  [18,  22,  20,  31,  38,  42],
        })

    # ── Req 3: Editable data table — writes changes back to session state ──────
    st.markdown("### 🗂️ Biometric Data Editor")
    st.caption("Edit any cell and click outside to apply. Changes are reflected live in the charts below.")

    edited_df = st.data_editor(
        st.session_state.health_metrics,
        use_container_width=True,
        hide_index=True,
        key="health_metrics_editor",
        column_config={
            "Month":             st.column_config.TextColumn("Month", disabled=True),
            "Resting_HR":        st.column_config.NumberColumn("Resting HR (bpm)",        min_value=40,  max_value=200),
            "Systolic_BP":       st.column_config.NumberColumn("Systolic BP (mmHg)",       min_value=80,  max_value=220),
            "Fasting_Glucose":   st.column_config.NumberColumn("Fasting Glucose (mg/dL)", min_value=50,  max_value=400),
            "Health_Risk_Score": st.column_config.NumberColumn("Health Risk Score (0–100)",min_value=0,   max_value=100),
        },
    )
    # Write edits back to session state immediately
    st.session_state.health_metrics = edited_df
    df = edited_df

    st.divider()

    # ── Req 4: st.columns(3) metric row ──────────────────────────────────────
    st.markdown("### 📍 Latest Readings")
    latest = df.iloc[-1]
    prev   = df.iloc[-2]

    risk_delta = int(latest["Health_Risk_Score"] - prev["Health_Risk_Score"])

    col1, col2, col3 = st.columns(3)

    # Column 1 — Health Risk Score with required delta + delta_color='inverse'
    col1.metric(
        label="⚠️ Health Risk Score",
        value=f"{int(latest['Health_Risk_Score'])} / 100",
        delta=risk_delta,
        delta_color="inverse",          # higher score = bad → red arrow up
    )
    col2.metric(
        label="💓 Resting HR",
        value=f"{int(latest['Resting_HR'])} bpm",
        delta=int(latest["Resting_HR"] - prev["Resting_HR"]),
        delta_color="inverse",
    )
    col3.metric(
        label="🩸 Fasting Glucose",
        value=f"{int(latest['Fasting_Glucose'])} mg/dL",
        delta=int(latest["Fasting_Glucose"] - prev["Fasting_Glucose"]),
        delta_color="inverse",
    )

    st.divider()

    # ── Req 5: Line chart — Health_Risk_Score (y) vs Month (x) ───────────────
    st.markdown("### 📈 Health Risk Score — 6-Month Trajectory")
    chart_df = df.set_index("Month")
    st.line_chart(
        chart_df[["Health_Risk_Score"]],
        height=300,
        use_container_width=True,
    )

    # Secondary supporting charts
    with st.expander("📊 View All Biometric Trend Charts", expanded=False):
        ca, cb = st.columns(2)
        with ca:
            st.markdown("**💓 Resting HR (bpm)**")
            st.line_chart(chart_df[["Resting_HR"]], height=200)
        with cb:
            st.markdown("**🩸 Fasting Glucose (mg/dL)**")
            st.line_chart(chart_df[["Fasting_Glucose"]], height=200)
        st.markdown("**🪀 Systolic BP (mmHg)**")
        st.line_chart(chart_df[["Systolic_BP"]], height=200)

    st.divider()

    # ── Req 6: AI Health Insight button ──────────────────────────────────────
    st.markdown("### 🤖 AI Preventative Health Coach")
    st.caption(
        "Click below to pass your current biometric data to Gemini for a "
        "personalised 3-point preventative wellness analysis."
    )

    if st.button(
        "✨ Generate AI Health Insight",
        key="generate_coach",
        type="primary",
        use_container_width=True,
    ):
        # Convert the live (possibly edited) DataFrame to a CSV string
        csv_string = df.to_csv(index=False)
        coach_prompt = (
            f"Here is the patient's 6-month biometric data in CSV format:\n\n"
            f"{csv_string}\n\n"
            "Please analyse the month-over-month trajectory and provide your "
            "3-bullet-point wellness recommendations."
        )

        with st.spinner(f"🧠 Health Coach is analysing your biometric trends in {st.session_state.app_language}..."):
            try:
                lang_coach_instruction = HEALTH_COACH_SYSTEM_INSTRUCTION + f"\n\nCRITICAL: You must provide your 3-bullet-point wellness recommendation and the CDSCO disclaimer entirely in {st.session_state.app_language}."
                response = groq_client.chat.completions.create(
                    model="openai/gpt-oss-20b",
                    messages=[
                        {"role": "system", "content": lang_coach_instruction},
                        {"role": "user", "content": coach_prompt}
                    ]
                )
                st.session_state.coach_recommendation = response.choices[0].message.content
            except Exception as exc:
                st.session_state.coach_recommendation = (
                    f"⚠️ **Groq API error:** `{exc}`"
                )

    # Display the AI response below the chart
    if st.session_state.coach_recommendation:
        st.markdown("---")
        st.markdown("#### 📝 Wellness Recommendations")
        st.markdown(st.session_state.coach_recommendation)
        if st.button("🗑️ Clear Recommendations", key="clear_coach"):
            st.session_state.coach_recommendation = None
            st.rerun()



